import 'fake-indexeddb/auto'
import { describe,it,expect,vi } from 'vitest'
import { roomFrom,project,opening } from '../etapa11/helpers'
import { buildPlanRoom,insertRoomPlacement,putRoomPlacement,worldPoint,inverseWorldPoint,floorRooms,cleanRoomPlacements,polygonsOverlap } from '../../src/floorPlan'
import { snapChoices,assistPlacements,planCompatibility,relationshipState } from '../../src/floorPlanConnections'
import { sharedPlanFaces } from '../../src/floorPlanFaces'
import { projectChecklistSummary } from '../../src/checklist'
import { cloneWithNewIds } from '../../src/projectClone'
import { SCHEMA_VERSION,createSnapshot,readSnapshot,saveWorkspace } from '../../src/storage'
function pair(length=3){const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,length,4,length]);[a,b].forEach(r=>r.walls.forEach(w=>w.thickness=.15));const p=project([a,b]);p.relationships=[{id:'shared',type:'shared_wall',sourceRoomId:a.id,sourceElementId:a.walls[1].id,targetRoomId:b.id,targetElementId:b.walls[3].id}];p.roomPlacements=[{roomId:a.id,floorId:'F1',x:0,y:0,rotation:0}];return {a,b,p}}
describe('Planta Geral — coordenadas e compatibilização',()=>{
 it('transforma e inverte coordenadas a 45° sem tocar no ambiente',()=>{const r=roomFrom('Sala',[4,3,4,3]),before=JSON.stringify(r),p={roomId:r.id,floorId:'F1',x:7.2,y:-3,rotation:45},point={x:2,y:1},back=inverseWorldPoint(worldPoint(point,p),p);expect(back.x).toBeCloseTo(2);expect(back.y).toBeCloseTo(1);buildPlanRoom(r);expect(JSON.stringify(r)).toBe(before)})
 it('permite inserção manual sem relações e mantém subambientes independentes',()=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Banheiro',[2,2,2,2]);b.parentRoomId=a.id;a.subrooms=[b];const p=project([a]),position=insertRoomPlacement(buildPlanRoom(a),[]),next=putRoomPlacement(p,position);expect(floorRooms(next,'F1')).toHaveLength(2);expect(next.roomPlacements).toHaveLength(1);expect(planCompatibility(next,'F1').alerts.some(x=>x.roomId===b.id)).toBe(true)})
 it('encaixa paredes internas de referência com espessura real sem sobreposição',()=>{const {a,b,p}=pair(),before=JSON.stringify(p.floors),choices=snapChoices(p,'F1',b.id);expect(choices).toHaveLength(1);const next=putRoomPlacement(p,choices[0].placement);expect(next.roomPlacements![1].x).toBeCloseTo(4.15);expect(relationshipState(next,p.relationships[0]).completed).toBe(true);expect(planCompatibility(next,'F1').alerts).toHaveLength(0);expect(JSON.stringify(next.floors)).toBe(before);expect(a.walls[1].lengthM).toBe(3)})
 it('aceita trecho parcial e exige escolha de referência sem acusar divergência',()=>{const {b,p}=pair(2.97),choices=snapChoices(p,'F1',b.id);expect(choices).toHaveLength(3);expect(choices[0].differenceM).toBe(0);const next=putRoomPlacement(p,choices[1].placement);expect(planCompatibility(next,'F1').alerts.some(a=>a.message.startsWith('Divergência:'))).toBe(false);expect(assistPlacements(p,'F1').added).toHaveLength(0)})
 it('mantém faces externas como referência opcional',()=>{const {a,b,p}=pair();a.wallMeasurementFace=b.wallMeasurementFace='external';const c=snapChoices(p,'F1',b.id)[0];expect(c.placement.x).toBeCloseTo(3.85);expect(b.walls[3].thickness).toBe(.15)})
 it('posiciona automaticamente apenas a solução única e preserva levantamento',()=>{const {p}=pair(),survey=projectChecklistSummary(p).completeness,result=assistPlacements(p,'F1');expect(result.added).toHaveLength(1);const next=putRoomPlacement(p,result.added[0]);expect(projectChecklistSummary(next).completeness).toBe(survey);expect(planCompatibility(next,'F1').percentage).toBe(100)})
 it('oferece quatro lados para adjacência sem decidir silenciosamente',()=>{const {b,p}=pair();p.relationships=[{id:'adj',type:'adjacency',sourceRoomId:p.floors[0].rooms[0].id,targetRoomId:b.id}];expect(snapChoices(p,'F1',b.id)).toHaveLength(4);expect(assistPlacements(p,'F1').added).toHaveLength(0);expect(assistPlacements(p,'F1').ambiguous).toContain(b.id)})
 it('detecta interior sobreposto mas permite bordas encostadas',()=>{const square=[{x:0,y:0},{x:2,y:0},{x:2,y:2},{x:0,y:2}];expect(polygonsOverlap(square,square)).toBe(true);expect(polygonsOverlap(square,square.map(p=>({...p,x:p.x+2})))).toBe(false);expect(polygonsOverlap(square,square.map(p=>({...p,x:p.x+1})))).toBe(true)})
 it('combina duas paredes compartilhadas em apenas duas faces',()=>{const {b,p}=pair(),next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement),shared=sharedPlanFaces(next,'F1',next.roomPlacements!);expect(shared.suppressed.size).toBe(2);expect(shared.faces).toHaveLength(1);expect(shared.faces[0].ranges).toHaveLength(2)})
 it('corta ambas as faces com aberturas presentes em qualquer parede',()=>{const {a,b,p}=pair();opening(a,{label:'P01',type:'door'},1);const next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement),ranges=sharedPlanFaces(next,'F1',next.roomPlacements!).faces[0].ranges;expect(ranges).toHaveLength(6);expect(p.floors[0].rooms[1].openings).toHaveLength(0)})
 it('encaixa portas vinculadas e oferece alternativas sem abertura correspondente',()=>{const {a,b,p}=pair(),doorA=opening(a,{label:'P01',type:'door'},1),doorB=opening(b,{label:'P02',type:'door',offsetM:1.7},3);p.relationships=[{id:'door',type:'opening_connection',sourceRoomId:a.id,sourceElementId:doorA.id,targetRoomId:b.id,targetElementId:doorB.id}];expect(snapChoices(p,'F1',b.id)).toHaveLength(1);const next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement);expect(relationshipState(next,p.relationships[0]).completed).toBe(true);p.relationships[0].targetElementId=undefined;opening(b,{label:'P03',type:'door'},0);expect(snapChoices(p,'F1',b.id)).toHaveLength(2);expect(assistPlacements(p,'F1').added).toHaveLength(0)})
 it('persiste posições e migra schema 6 sem alterar números',()=>{const {p}=pair(),data={projects:[p],projectId:p.id,floorId:'F1',roomId:p.floors[0].rooms[0].id},snapshot=createSnapshot(data);expect(snapshot.schemaVersion).toBe(SCHEMA_VERSION);expect(readSnapshot(snapshot).data.projects[0].roomPlacements).toEqual(p.roomPlacements);const migrated=readSnapshot({...snapshot,schemaVersion:6});expect(migrated.data.projects[0].floors[0].rooms[0].walls).toEqual(p.floors[0].rooms[0].walls)})
 it('remapeia IDs da cópia e remove posição após exclusão de ambiente',()=>{const {p}=pair(),clone=cloneWithNewIds(p);expect(clone.project.roomPlacements![0].roomId).toBe(clone.idMap.get(p.roomPlacements![0].roomId));expect(clone.project.roomPlacements![0].floorId).toBe(clone.idMap.get('F1'));expect(clone.project.roomPlacements![0].x).toBe(0);expect(cleanRoomPlacements({...p,floors:[]}).roomPlacements).toEqual([])})
 it('detecta sobreposição inesperada e relação sem elemento correspondente',()=>{const {a,b,p}=pair();p.roomPlacements!.push({roomId:b.id,floorId:'F1',x:1,y:1,rotation:0});expect(planCompatibility(p,'F1').alerts.some(x=>x.message.startsWith('Sobreposição'))).toBe(true);p.relationships[0].targetElementId='inexistente';expect(planCompatibility(p,'F1').alerts.some(x=>x.message.includes('sem elemento'))).toBe(true);expect(a.walls[1].lengthM).toBe(3)})
 it('não usa comprimento provisório como medida para snap',()=>{const {a,b,p}=pair();a.walls[1].lengthM=null;expect(snapChoices(p,'F1',b.id)).toHaveLength(0);expect(assistPlacements(p,'F1').added).toHaveLength(0)})
 it('não sinaliza como sobreposição a parede de ambientes medidos pela face externa',()=>{const {a,b,p}=pair();a.wallMeasurementFace=b.wallMeasurementFace='external';const next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement);expect(planCompatibility(next,'F1').alerts).toEqual([])})
 it('mantém o encaixe com referência rotacionada a 45° e faces limpas',()=>{const {b,p}=pair();p.roomPlacements![0].rotation=45;p.roomPlacements![0].x=-2.123;p.roomPlacements![0].y=7.456;const next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement);expect(next.roomPlacements![1].rotation).toBeCloseTo(45);expect(relationshipState(next,p.relationships[0]).completed).toBe(true);expect(sharedPlanFaces(next,'F1',next.roomPlacements!).faces[0].ranges).toHaveLength(2)})
 it('reabre no IndexedDB com coordenadas e rotação exatas',async()=>{const {p}=pair();p.roomPlacements![0]={...p.roomPlacements![0],x:-3.123456789,y:8.123456789,rotation:82.123456789};await saveWorkspace(createSnapshot({projects:[p],projectId:p.id,floorId:'F1',roomId:p.roomPlacements![0].roomId}));vi.resetModules();const storage=await import('../../src/storage'),loaded=await storage.loadWorkspace();expect(loaded?.data.projects[0].roomPlacements).toEqual(p.roomPlacements)})
 it('rejeita posições inválidas ou duplicadas sem alterar o arquivo original',()=>{const {p}=pair(),snapshot=createSnapshot({projects:[p],projectId:p.id,floorId:'F1',roomId:p.roomPlacements![0].roomId});p.roomPlacements!.push({...p.roomPlacements![0]});expect(()=>readSnapshot(snapshot)).toThrow('Posições');p.roomPlacements!.pop();p.roomPlacements![0].rotation=Infinity;expect(()=>readSnapshot(snapshot)).toThrow('Posições')})
})
