import { describe,it,expect } from 'vitest'
import { roomFrom,project,opening } from '../etapa11/helpers'
import { SHEETS,SCALES,paperSize,mmOnPaper,fits,fittingOptions } from '../../src/pdf/sheetLayout'
import { drawRoomSheet,roomSheetPdf,roomExtent } from '../../src/pdf/roomSheet'
import { drawPlanSheet,planSheetPdf } from '../../src/pdf/planSheet'
import { drawRoofSheet,roofSheetPdf,roofExtent } from '../../src/pdf/roofSheet'
import { defaultPdfLayers,scaleBar } from '../../src/pdf/sheetDecorations'
import { createRoof } from '../../src/roofs'
import { snapChoices } from '../../src/floorPlanConnections'
import { putRoomPlacement } from '../../src/floorPlan'
const option={sheet:'A3',orientation:'landscape',scale:50} as const
const text=(bytes:Uint8Array)=>new TextDecoder('latin1').decode(bytes)
describe('Etapa 23 — PDF vetorial em escala real',()=>{
 it('define as cinco folhas ISO e doze escalas solicitadas',()=>{expect(SHEETS).toEqual({A4:{width:210,height:297},A3:{width:297,height:420},A2:{width:420,height:594},A1:{width:594,height:841},A0:{width:841,height:1189}});expect(SCALES).toEqual([10,20,25,50,75,100,125,150,200,250,500,1000]);for(const sheet of Object.keys(SHEETS) as (keyof typeof SHEETS)[])expect(paperSize({sheet,orientation:'landscape'})).toEqual({width:SHEETS[sheet].height,height:SHEETS[sheet].width})})
 it.each(SCALES)('mantém escala física uniforme 1:%s e não usa ajuste à folha',scale=>{const r=roomFrom('Sala',[5,4,5,4]),p=project([r]),draw=drawRoomSheet({project:p,room:r,option:{sheet:'A0',orientation:'landscape',scale}}),a=draw.toPaper({x:0,y:0}),b=draw.toPaper({x:5,y:0}),c=draw.toPaper({x:0,y:5});expect(Math.hypot(b.x-a.x,b.y-a.y)).toBeCloseTo(mmOnPaper(5,scale),9);expect(Math.hypot(c.x-a.x,c.y-a.y)).toBeCloseTo(mmOnPaper(5,scale),9)})
 it('reutiliza as faces físicas: 150 mm em 1:50 são 3 mm sem preenchimento',()=>{const r=roomFrom('Sala',[5,4,5,4]);r.walls.forEach(w=>w.thickness=.15);const {page,toPaper}=drawRoomSheet({project:project([r]),room:r,option}),a=toPaper({x:1,y:0}),b=toPaper({x:1,y:-.15});expect(Math.abs(a.y-b.y)).toBeCloseTo(3);expect(page.ops.slice(0,4).join(' ')).not.toContain(' re ');expect(r.walls[0].lengthM).toBe(5)})
 it('usa os placements com rotação e não reposiciona ambientes',()=>{const r=roomFrom('Sala',[5,4,5,4]),p=project([r]);p.roomPlacements=[{roomId:r.id,floorId:'F1',x:-25.123,y:17.987,rotation:45}];const before=JSON.stringify(p),{toPaper}=drawPlanSheet({project:p,floor:p.floors[0],option});expect(Math.hypot(toPaper({x:0,y:0}).x-toPaper({x:5,y:0}).x,toPaper({x:0,y:0}).y-toPaper({x:5,y:0}).y)).toBeCloseTo(100);expect(JSON.stringify(p)).toBe(before);expect(text(planSheetPdf({project:p,floor:p.floors[0],option}).bytes)).not.toContain('/Subtype /Image')})
 it('planta compartilhada conserva somente duas faces e cortes das aberturas',()=>{const a=roomFrom('A',[4,3,4,3]),b=roomFrom('B',[4,3,4,3]);[a,b].forEach(r=>r.walls.forEach(w=>w.thickness=.15));const p=project([a,b]);p.relationships=[{id:'rel',type:'shared_wall',sourceRoomId:a.id,sourceElementId:a.walls[1].id,targetRoomId:b.id,targetElementId:b.walls[3].id}];p.roomPlacements=[{roomId:a.id,floorId:'F1',x:0,y:0,rotation:0}];opening(a,{label:'P01',type:'door'},1);const next=putRoomPlacement(p,snapChoices(p,'F1',b.id)[0].placement),draw=drawPlanSheet({project:next,floor:next.floors[0],option,layers:{...defaultPdfLayers,ids:false,names:false,measurements:false,openings:false}});const lines=draw.page.ops.filter(op=>op.endsWith(' l S'));expect(lines.length).toBe(19) // 12 external segments + 4 cut shared faces + 2 real jambs + frame separator
 })
 it('oculta camadas sem mudar medidas e exclui fotos da planta',()=>{const r=roomFrom('Sala',[5,4,5,4]);r.displayId='AMB-009';const p=project([r]);p.roomPlacements=[{roomId:r.id,floorId:'F1',x:0,y:0,rotation:0}];const pdf=text(planSheetPdf({project:p,floor:p.floors[0],option,layers:{...defaultPdfLayers,walls:false,ids:false,names:false,measurements:false,openings:false}}).bytes);expect(pdf).not.toContain('AMB-009');expect(pdf).not.toContain('/Subtype /Image');expect(r.walls[0].lengthM).toBe(5)})
 it('sugere opções para galpão de milhares de metros quadrados e recusa escala que não cabe',()=>{const r=roomFrom('Galpão',[120,80,120,80]),p=project([r]),extent=roomExtent(r),options=fittingOptions(extent);expect(options.length).toBeGreaterThan(0);expect(options.every(o=>fits(extent,o))).toBe(true);expect(()=>drawRoomSheet({project:p,room:r,option:{sheet:'A4',orientation:'portrait',scale:10}})).toThrow('não cabe');expect(r.walls[0].lengthM).toBe(120)})
 it('mantém barra gráfica dentro do carimbo em todas as escalas',()=>{for(const scale of SCALES){const bar=scaleBar(scale);expect(bar.widthMm).toBeLessThanOrEqual(65);expect(bar.widthMm).toBeCloseTo(mmOnPaper(bar.totalM,scale));expect(bar.totalM).toBeGreaterThan(0)}})
 it('exporta todas as águas, alturas, inclinações e observações do telhado',()=>{const p=project([]),roof=createRoof(p);roof.lengthM=8;roof.widthM=6;roof.name='Cobertura';roof.note='Conferir encontro com fachada.';roof.waters.forEach((w,i)=>Object.assign(w,{highSide:'Cumeeira',lowSide:'Beiral',highHeightM:4.5,lowHeightM:3,projectionM:3,direction:i?'south':'north'}));const before=JSON.stringify(roof),roofOption={...option,sheet:'A2' as const,orientation:'portrait' as const},draw=drawRoofSheet({project:p,roof,option:roofOption}),pdf=text(roofSheetPdf({project:p,roof,option:roofOption,responsible:'Jean'}).bytes);expect(draw.extent.valid).toHaveLength(2);expect(pdf).toContain('TEL-001');expect(pdf).toContain('AG-01');expect(pdf).toContain('AG-02');expect(pdf).toContain('50%');expect(pdf).toContain('Jean');expect(pdf).toContain('Conferir encontro com fachada.');expect(pdf).not.toContain('/Subtype /Image');expect(JSON.stringify(roof)).toBe(before);expect(Math.abs(draw.toPaper({x:5,y:0}).x-draw.toPaper({x:0,y:0}).x)).toBeCloseTo(100);expect(fittingOptions(o=>roofExtent(p,roof,o)).length).toBeGreaterThan(0)})
})
