import {it,expect} from 'vitest'
import {createRoom} from '../../src/domain'
import type {Project} from '../../src/models'
import {createRevitExchange} from '../../src/revitExport'
function fixture(){const room=createRoom('Sala','f');room.ceilingHeightM=3;room.ceilingType='slab';room.walls=[4,3,4,3].map((lengthM,i)=>({id:`w${i}`,label:String.fromCharCode(65+i),lengthM,thickness:.15}));const project:Project={id:'p',name:'Teste',floors:[{id:'f',name:'Térreo',rooms:[room]}],relationships:[],roomPlacements:[{roomId:room.id,floorId:'f',x:10,y:20,rotation:90}]};return {project,room}}
it('preserva medidas e usa transformação rígida com eixo Y convertido',()=>{const {project}=fixture(),original=JSON.stringify(project),data=createRevitExchange(project,'f',2);expect(data.walls).toHaveLength(4);expect(data.walls[0].measuredLengthM).toBe(4);expect(data.walls[0].start[2]).toBe(2);expect(data.walls[0].start[0]).toBeCloseTo(10.075);expect(data.walls[0].start[1]).toBeCloseTo(-19.925);expect(data.walls[0].heightM).toBe(3);expect(JSON.stringify(project)).toBe(original)})
it('não inventa posicionamento, altura ou elevação',()=>{const {project,room}=fixture();expect(()=>createRevitExchange(project,'f',NaN)).toThrow();project.roomPlacements=[];expect(()=>createRevitExchange(project,'f',0)).toThrow();project.roomPlacements=[{roomId:room.id,floorId:'f',x:0,y:0,rotation:0}];room.ceilingHeightM=-1;expect(()=>createRevitExchange(project,'f',0)).toThrow()})
it('consolida parede parcial mesmo com alturas diferentes',()=>{const {project,room}=fixture();project.roomPlacements![0]={roomId:room.id,floorId:'f',x:0,y:0,rotation:0};const other=createRoom('Anexo','f');other.ceilingHeightM=3.5;other.ceilingType='slab';other.walls=[{id:'shared',label:'A',lengthM:2,thickness:.15}];room.walls[0].sharedWallReference={roomId:other.id,wallId:'shared'};project.floors[0].rooms.push(other);project.roomPlacements!.push({roomId:other.id,floorId:'f',x:1,y:0,rotation:0});const result=createRevitExchange(project,'f',0);expect(result.walls.length).toBeGreaterThan(0);expect(result.walls.some(w=>w.heightM===3.5)).toBe(true)})

import {roomWallHeight} from '../../src/ceilingHeight'
it('PD padrão 2,50; forro soma 0,50 e laje não soma',()=>{expect(roomWallHeight({ceilingHeightM:null}).wallHeightM).toBe(3);expect(roomWallHeight({ceilingHeightM:2.8,ceilingType:'suspended'}).wallHeightM).toBe(3.3);expect(roomWallHeight({ceilingHeightM:2.8,ceilingType:'slab'}).wallHeightM).toBe(2.8);expect(roomWallHeight({ceilingHeightM:null,ceilingType:'slab'}).wallHeightM).toBe(2.5)})

import {wallConflicts} from '../../src/wallConflicts'
it('alerta parede coincidente sem vínculo, sem mudar os dados',()=>{const {project,room}=fixture();project.roomPlacements![0]={roomId:room.id,floorId:'f',x:0,y:0,rotation:0};const other={...room,id:'other',name:'Outro',walls:room.walls.map(w=>({...w,id:w.id+'other'}))};project.floors[0].rooms.push(other);project.roomPlacements!.push({roomId:'other',floorId:'f',x:0,y:0,rotation:0});const original=JSON.stringify(project);expect(wallConflicts(project,'f',project.roomPlacements!)).toHaveLength(4);expect(()=>createRevitExchange(project,'f',0)).toThrow('Conflito de paredes');expect(JSON.stringify(project)).toBe(original);project.roomPlacements![1].x=10;expect(wallConflicts(project,'f',project.roomPlacements!)).toHaveLength(0)})
import {uniteSuggestedWalls} from '../../src/wallConflicts'
it('união sugerida exige confirmação explícita e preserva geometria e IDs',()=>{const {project,room}=fixture();const other={...room,id:'other',name:'Outro',walls:room.walls.map(w=>({...w,id:w.id+'other'}))};project.floors[0].rooms.push(other);project.roomPlacements!.push({...project.roomPlacements![0],roomId:'other'});const suggestion=wallConflicts(project,'f',project.roomPlacements!)[0];expect(suggestion.canUnite).toBe(true);const next=uniteSuggestedWalls(project,'f',suggestion);expect(next.spatialConnections).toHaveLength(1);expect(next.roomPlacements).toEqual(project.roomPlacements);expect(next.floors).toEqual(project.floors);expect(wallConflicts(next,'f',next.roomPlacements!).some(c=>c.wallId===suggestion.wallId&&c.otherWallId===suggestion.otherWallId)).toBe(false);expect(uniteSuggestedWalls(next,'f',suggestion)).toBe(next)})

import {reconcileSpatialConnections} from '../../src/spatialConnections'
import {connectedAssembly} from '../../src/planAssembly'
it('união secundária não muda grupo principal nem desaparece ao salvar',()=>{const {project,room}=fixture();const other={...room,id:'other',walls:room.walls.map(w=>({...w,id:w.id+'other'}))};project.floors[0].rooms.push(other);project.roomPlacements!.push({...project.roomPlacements![0],roomId:'other'});const next=reconcileSpatialConnections(uniteSuggestedWalls(project,'f',wallConflicts(project,'f',project.roomPlacements!)[0]));expect(next.spatialConnections?.[0].secondary).toBe(true);expect(next.spatialConnections?.[0].assemblyLocked).toBe(false);expect(connectedAssembly(next,room.id)).toEqual(connectedAssembly(project,room.id));expect(next.roomPlacements).toEqual(project.roomPlacements)})
import {getWallReferences} from '../../src/openings'
it('duas pontas vinculadas exportam uma abertura física com ambos IDs',()=>{const {project,room}=fixture();room.openings=[{id:'door1',label:'P01',type:'door',wallId:room.walls[0].id,referenceCornerId:getWallReferences(room.walls,[],room.walls[0].id)[0].id,offsetM:1,widthM:1,heightM:2,sillHeightM:null,connectedRoomId:'other',connectedOpeningId:'door2'}];const other={...room,id:'other',name:'Outro',walls:room.walls.map(w=>({...w,id:w.id+'other'})),openings:[] as typeof room.openings};other.openings=[{...room.openings[0],id:'door2',wallId:other.walls[0].id,referenceCornerId:getWallReferences(other.walls,[],other.walls[0].id)[0].id,connectedRoomId:room.id,connectedOpeningId:'door1'}];room.walls.forEach((w,i)=>w.sharedWallReference={roomId:other.id,wallId:other.walls[i].id});project.floors[0].rooms.push(other);project.roomPlacements!.push({...project.roomPlacements![0],roomId:'other'});const result=createRevitExchange(project,'f',0);expect(result.openings).toHaveLength(1);expect(result.openings[0].sourceRefs).toHaveLength(2);other.openings[0].offsetM=1.3;expect(()=>createRevitExchange(project,'f',0)).toThrow('desalinhadas')})
