import 'fake-indexeddb/auto'
import {describe,it,expect} from 'vitest'
import {renderToStaticMarkup} from 'react-dom/server'
import {roomFrom,project,opening} from '../etapa11/helpers'
import {reconcileRelationships,projectRooms} from '../../src/relationships'
import {nextProjectOpeningSequence,availableCounterpart} from '../../src/spatialConnections'
import {recalculateChecklist,roomChecklist,projectChecklistSummary} from '../../src/checklist'
import {createRoom,updateRoom,wallLabel} from '../../src/domain'
import {nextWallIndex,removePerimeterWall} from '../../src/deletions'
import {nextRoomSequence} from '../../src/projectMetadata'
import {createRoomObject,nextObjectSequence,buildObjectPlacements} from '../../src/roomObjects'
import {createStructuralObject,nextStructuralSequence} from '../../src/structural'
import {createRoof,nextRoofSequence,changeWaterCount,roofSlope,roofChecklist} from '../../src/roofs'
import {buildPerimeter} from '../../src/geometry'
import {buildPlanRoom,worldPoint,pointDistance} from '../../src/floorPlan'
import {snapChoices,relationshipState} from '../../src/floorPlanConnections'
import {cornerSnap} from '../../src/cornerConnections'
import {roomGhosts} from '../../src/roomGhosts'
import {drawRoomSheet} from '../../src/pdf/roomSheet'
import {drawPlanSheet} from '../../src/pdf/planSheet'
import {defaultPdfLayers} from '../../src/pdf/sheetDecorations'
import {scopedPdf} from '../../src/pdf/scopedSheets'
import {scopedProject} from '../../src/exportScope'
import {createBackup,parseBackup,importProjects} from '../../src/exporting'
import {createSnapshot,saveWorkspace,loadWorkspace,encodeSnapshot,decodeSnapshot} from '../../src/storage'
import OpeningEditor from '../../src/OpeningEditor'
import RoomEditor from '../../src/RoomEditor'
import InternalWallEditor from '../../src/InternalWallEditor'
import Sketch from '../../src/Sketch'
import {buildRoomGeometry} from '../../src/roomGeometry'
import type {SpatialConnection} from '../../src/models'

const option={sheet:'A3',orientation:'landscape',scale:50} as const
function pair(){const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,3,4,3]),c=roomFrom('Quarto',[4,3,4,3]);const oa=opening(a,{type:'gap',label:'V01'},1),ob=opening(b,{type:'gap',label:'V02'},3);oa.connectedRoomId=b.id;oa.connectedOpeningId=ob.id;const p=reconcileRelationships(project([a,b,c]));return {p,a:p.floors[0].rooms[0],b:p.floors[0].rooms[1],c:p.floors[0].rooms[2]}}
describe('Etapa 25 — regressões obrigatórias',()=>{
 it('preencher/apagar controla OK/PENDENTE e preserva N/A',()=>{const r=roomFrom('Sala',[4,3,4,3]),p=project([r]);p.generalChecks={client:{status:'pending',value:'Cliente'}};let next=recalculateChecklist(p);expect(next.generalChecks?.client.status).toBe('ok');expect(next.floors[0].rooms[0].technicalChecks?.walls.status).toBe('ok');next.generalChecks!.client.value='';next.floors[0].rooms[0].walls[0].lengthM=null;next=recalculateChecklist(next);expect(next.generalChecks?.client.status).toBe('pending');expect(next.floors[0].rooms[0].technicalChecks?.walls.status).toBe('pending');next.generalChecks!.client.status='na';next.floors[0].rooms[0].technicalChecks!.walls.status='na';next=recalculateChecklist(next);expect(next.generalChecks?.client.status).toBe('na');expect(next.floors[0].rooms[0].technicalChecks?.walls.status).toBe('na')})
 it('calcula % a partir de obrigações únicas e ignora fotos',()=>{const r=roomFrom('Sala',[4,3,4,3]),p=project([r]),before=roomChecklist(r,p);expect(before.completeness).toBe(Math.round(100*before.obligations.filter(o=>o.completed).length/before.obligations.length));r.photos=[{id:'ph',roomId:r.id,createdAt:'2026-10-05',originalFileName:'a.jpg',tags:[],fileId:'file',mimeType:'image/jpeg',size:1}];expect(roomChecklist(r,p).completeness).toBe(before.completeness);expect(roomChecklist(r,p).photosCount).toBe(1)})
 it('reutiliza primeiro ID livre por tipo sem reciclar UUID',()=>{const r=roomFrom('Sala',[4,3,4,3]);opening(r,{type:'door',label:'P02'});opening(r,{type:'gap',label:'V01'});opening(r,{type:'gap',label:'V03'});const p=project([r]);p.openingCounters={door:99,gap:99,window:99};expect(nextProjectOpeningSequence(p,'door')).toBe(1);expect(nextProjectOpeningSequence(p,'gap')).toBe(2);r.openings=r.openings.filter(o=>o.label!=='V03');opening(r,{type:'gap',label:'V02'});expect(nextProjectOpeningSequence(p,'gap')).toBe(3);r.displayId='AMB-002';p.roomDisplayCounter=99;expect(nextRoomSequence(p)).toBe(1);expect(wallLabel(nextWallIndex(removePerimeterWall(r,r.walls[1].id)))).toBe('B');const o=createRoomObject(r);r.objects=[o];r.objectCounter=99;r.objects=[];expect(nextObjectSequence(r)).toBe(1);expect(createRoomObject(r).id).not.toBe(o.id);r.structuralCounters={beam:99,column:99};expect(nextStructuralSequence(r,'beam')).toBe(1);p.roofCounter=99;expect(nextRoofSequence(p)).toBe(1)})
 it('mantém uma abertura física, bloqueia terceiro uso e sincroniza as dimensões',()=>{const {p,a,b,c}=pair();expect(a.openings[0].label).toBe(b.openings[0].label);expect(p.spatialConnections?.filter(x=>x.type==='opening')).toHaveLength(1);expect(p.relationships).toHaveLength(1);const other=opening(c,{type:'gap',label:'V03'});expect(availableCounterpart(other,c.id,b.openings[0])).toBe(false);other.connectedRoomId=b.id;other.connectedOpeningId=b.openings[0].id;const rejected=reconcileRelationships(p);expect(rejected.floors[0].rooms[2].openings[0].connectedOpeningId).toBeUndefined();const next=structuredClone(rejected);next.floors[0].rooms[0].openings[0].widthM=1.2;next.floors[0].rooms[0].openings[0].heightM=2.4;const synced=reconcileRelationships(next,rejected);expect(synced.floors[0].rooms[1].openings[0].widthM).toBe(1.2);expect(synced.floors[0].rooms[1].openings[0].heightM).toBe(2.4)})
 it('excluir contraparte limpa referência e libera ID apenas quando não há outra ponta',()=>{const {p,a}=pair(),next=structuredClone(p);next.floors[0].rooms[1].openings=[];const result=reconcileRelationships(next,p);expect(result.floors[0].rooms[0].openings[0].connectedOpeningId).toBeUndefined();expect(nextProjectOpeningSequence(result,'gap')).toBe(2);result.floors[0].rooms[0].openings=[];expect(nextProjectOpeningSequence(result,'gap')).toBe(1);expect(a.openings[0].label).toBe('V01')})
 it('preserva a Sala e seu placement ao criar destino do vínculo',()=>{const a=roomFrom('Sala',[4,3,4,3]),p=project([a]),o=opening(a,{type:'gap',label:'V01'}),before=structuredClone(a),kitchen=createRoom('Cozinha','F1');o.connectedRoomId=kitchen.id;p.roomPlacements=[{roomId:a.id,floorId:'F1',x:9.1,y:-3.2,rotation:45}];const next=reconcileRelationships({...p,floors:[{...p.floors[0],rooms:[a,kitchen]}]},p);expect(next.floors[0].rooms[0].walls).toEqual(before.walls);expect(next.roomPlacements).toEqual(p.roomPlacements);expect(projectRooms(next).find(r=>r.id===kitchen.id)?.name).toBe('Cozinha');expect(next.floors[0].rooms[0].openings[0].connectedRoomId).toBe(kitchen.id);const html=renderToStaticMarkup(<OpeningEditor project={next} room={kitchen} onChange={()=>{}} onProjectChange={()=>{}} checks={[]} relatedRooms={[{room:next.floors[0].rooms[0],path:'Sala'}]}/>);expect(html).toContain('Aberturas nas paredes')
 })
 it.each(['internal','external'] as const)('cantos %s com orientação normal/invertida e snap preservam medidas',face=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,3,4,3]);[a,b].forEach(r=>r.walls.forEach(w=>w.thickness=.15));for(const orientation of ['normal','inverted'] as const){const connection:SpatialConnection={id:'corner',type:'corner',a:{roomId:a.id,elementId:a.corners[1].id,face},b:{roomId:b.id,elementId:b.corners[3].id,face},orientation},anchor={roomId:a.id,floorId:'F1',x:5,y:-1,rotation:45},p=reconcileRelationships({...project([a,b]),spatialConnections:[connection],roomPlacements:[anchor]});const snap=cornerSnap(connection,a,b,anchor)!;p.roomPlacements!.push(snap);expect(relationshipState(p,p.relationships.find(r=>r.type==='corner')!).completed).toBe(true);expect(snapChoices(p,'F1',b.id)[0].placement).toEqual(snap);expect(a.walls[0].lengthM).toBe(4)}})
 it('fantasmas usam posição real, sem desenhar subambiente por mera hierarquia',()=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Anexo',[2,2,2,2]);a.subrooms=[b];b.parentRoomId=a.id;const p=project([a]);expect(roomGhosts(p,a)).toEqual([]);p.roomPlacements=[{roomId:a.id,floorId:'F1',x:2,y:1,rotation:90},{roomId:b.id,floorId:'F1',x:2,y:6,rotation:90}];const ghost=roomGhosts(p,a)[0];expect(ghost.segments[0].start.x).toBeCloseTo(5);expect(ghost.segments[0].start.y).toBeCloseTo(0);expect(renderToStaticMarkup(<Sketch project={p} room={a}/>)).toContain('room-ghost')})
 it('4×3 m e objeto 1×0,60 m têm a mesma proporção no croqui, Planta Geral e PDF',()=>{const r=roomFrom('Sala',[4,3,4,3]),object={...createRoomObject(r),name:'Mesa',dimensions:{widthM:1,depthM:.6},position:{xM:2,yM:1.5}};r.objects=[object];const p=project([r]),geometry=buildPerimeter(r.walls,r.corners),o=buildObjectPlacements(r.objects)[0];expect(o.widthM*geometry.scale/(4*geometry.scale)).toBeCloseTo(.25);expect(o.heightM*geometry.scale/(3*geometry.scale)).toBeCloseTo(.2);p.roomPlacements=[{roomId:r.id,floorId:'F1',x:11,y:-5,rotation:45}];const placement=p.roomPlacements[0],plan=buildPlanRoom(r);expect(plan.objects[0].widthM).toBe(1);const length=pointDistance(worldPoint({x:0,y:0},placement),worldPoint({x:1,y:0},placement));expect(length/pointDistance(worldPoint({x:0,y:0},placement),worldPoint({x:4,y:0},placement))).toBeCloseTo(.25);const html=renderToStaticMarkup(<Sketch room={r}/>);expect(html).toContain('object-shape');for(const draw of [drawRoomSheet({project:p,room:r,option}),drawPlanSheet({project:p,floor:p.floors[0],option})]){const width=pointDistance(draw.toPaper({x:0,y:0}),draw.toPaper({x:1,y:0}));expect(width).toBeCloseTo(20);expect(width/pointDistance(draw.toPaper({x:0,y:0}),draw.toPaper({x:4,y:0}))).toBeCloseTo(.25);expect(pointDistance(draw.toPaper({x:0,y:0}),draw.toPaper({x:0,y:.6}))).toBeCloseTo(12)}})
 it.each([1,2,3,4] as const)('telhado %s águas aceita inclinação sem alturas e não corrige inconsistências',count=>{const p=project([]),roof=changeWaterCount(createRoof(p),count);roof.lengthM=8;roof.widthM=5;roof.waters.forEach((w,i)=>Object.assign(w,{inclinationPercent:10+i,direction:'south',highHeightM:1,lowHeightM:4,projectionM:-1}));const before=structuredClone(roof);expect(roofChecklist(roof).completeness).toBe(100);roof.waters.forEach(w=>expect(roofSlope(w)?.percent).toBe(w.inclinationPercent));expect(roof).toEqual(before)})
 it.each(['A4','A3','A2','A1','A0'] as const)('PDF %s mantém escala física e vetor',sheet=>{const r=roomFrom('Sala',[4,3,4,3]),p=project([r]);p.roomPlacements=[{roomId:r.id,floorId:'F1',x:10,y:-1,rotation:45}];const o={...option,sheet,scale:100},draw=drawRoomSheet({project:p,room:r,option:o});expect(pointDistance(draw.toPaper({x:0,y:0}),draw.toPaper({x:4,y:0}))).toBeCloseTo(40);for(const scope of ['room','floor','plan','project'] as const){const file=scopedPdf(p,scope,'F1',r.id,o,defaultPdfLayers),text=new TextDecoder().decode(file.bytes);expect(text).toContain('/Type /Page');expect(text).not.toContain('/Subtype /Image')}})
 it('IndexedDB e JSON preservam UUIDs, vínculos e placement exatos',async()=>{const {p,a}=pair();p.roomPlacements=[{roomId:a.id,floorId:'F1',x:-2.123456789,y:8.987654321,rotation:82}];const data={projects:[p],projectId:p.id,floorId:'F1',roomId:a.id};await saveWorkspace(createSnapshot(data));expect((await loadWorkspace())?.data.projects[0]).toEqual(p);const backup=parseBackup(createBackup(data).text);expect(backup.data.projects[0]).toEqual(p);expect(decodeSnapshot(encodeSnapshot(createSnapshot(data))).data.projects[0]).toEqual(p)})
 it('backup de ambiente não apaga outros ambientes na restauração',()=>{const {p,a,b}=pair(),data={projects:[p],projectId:p.id,floorId:'F1',roomId:a.id},selected=scopedProject(p,'room','F1',a.id);selected.floors[0].rooms[0].name='Sala restaurada';const imported=importProjects(data,parseBackup(createBackup({...data,projects:[selected]}).text)).data.projects[0];expect(projectRooms(imported)).toHaveLength(3);expect(projectRooms(imported).find(r=>r.id===b.id)?.name).toBe('Cozinha');expect(projectRooms(imported).find(r=>r.id===a.id)?.name).toBe('Sala restaurada');expect(imported.spatialConnections).toHaveLength(1)})
})
