import type { Project,Roof } from '../models'
import { roofSlope,roofDirections } from '../roofs'
import { formatMeasurement } from '../units'
import { PdfPage,buildPdf } from './pdfWriter'
import { drawingArea,fitMessage,paperSize,LABEL_ROOM_MM } from './sheetLayout'
import type { SheetOption } from './sheetLayout'
import { drawTitleBlock,wrapText } from './sheetDecorations'
const positive=(n:number|null)=>n!=null&&Number.isFinite(n)&&n>0
function roofDetails(project:Project,roof:Roof,option:SheetOption) {const width=drawingArea(option).width-2*LABEL_ROOM_MM,format=(n:number|null|undefined)=>formatMeasurement(n,project.measurementUnit??'m'),lines=[`Forma: ${roof.shape==='square'?'quadrada':'retangular'} · ${roof.waterCount} águas · ${format(roof.lengthM)} × ${format(roof.widthM)}`, 'Divisão das águas e cumeeira: esquema. Dimensões externas e perfis medidos em escala.',...roof.waters.flatMap(w=>{const s=roofSlope(w);return [`${w.displayId} · Alto: ${w.highSide||'?'} (${format(w.highHeightM)}) · Baixo: ${w.lowSide||'?'} (${format(w.lowHeightM)})`,`Projeção: ${format(w.projectionM)} · Caimento: ${w.direction?roofDirections[w.direction]:'não informado'} · ${s?`Desnível ${format(s.riseM)} · ≈ ${s.percent.toLocaleString('pt-BR',{maximumFractionDigits:2})}% · ≈ ${s.degrees.toLocaleString('pt-BR',{maximumFractionDigits:2})}°`:'Inclinação: dados insuficientes.'}`]}),...(roof.note?[`Observações: ${roof.note}`]:[])];return lines.flatMap(line=>wrapText(line,width,2.7))}
export function roofExtent(project:Project,roof:Roof,option:SheetOption) {const valid=roof.waters.filter(w=>roofSlope(w) && w.highHeightM!=null && w.lowHeightM!=null && w.projectionM!=null && w.projectionM>0 && w.highHeightM>=w.lowHeightM && w.lowHeightM>=0),profilesHeight=valid.reduce((sum,w)=>sum+w.highHeightM!,0),details=roofDetails(project,roof,option);return {width:Math.max(roof.lengthM??0,...valid.map(w=>w.projectionM!)),height:(roof.widthM??0)+profilesHeight,extraHeightMm:details.length*3.5+valid.length*18+14,details,valid}}
export function drawRoofSheet({project,roof,option,date=new Date(),responsible}:{project:Project;roof:Roof;option:SheetOption;date?:Date;responsible?:string}) {
 if(!positive(roof.lengthM)||!positive(roof.widthM))throw new Error('Informe comprimento e largura positivos para exportar o telhado em escala.')
 const extent=roofExtent(project,roof,option),problem=fitMessage(extent,option);if(problem)throw new Error(problem.replace('O ambiente','A ficha de telhado'))
 const paper=paperSize(option),area=drawingArea(option),page=new PdfPage(paper.width,paper.height),k=1000/option.scale,x=area.x+LABEL_ROOM_MM,y=area.y+LABEL_ROOM_MM,w=roof.lengthM!*k,h=roof.widthM!*k,f=(n:number|null|undefined)=>formatMeasurement(n,project.measurementUnit??'m'),toPaper=(p:{x:number;y:number})=>({x:x+p.x*k,y:y+p.y*k})
 page.text({x,y:y-6},`${roof.displayId} — Vista superior`,3.2,{font:'bold'});page.rect(x,y,w,h,{width:.35})
 const count=roof.waterCount,m=h/2,a=count===4?w*.25:0,b=count===4?w*.75:count===3?w*.75:w,polygons=count===1?[[[0,0],[w,0],[w,h],[0,h]]]:[[[0,0],[w,0],[b,m],[a,m]],[[0,h],[w,h],[b,m],[a,m]],...(count===4?[[[0,0],[a,m],[0,h]]]:[]),...(count>=3?[[[w,0],[b,m],[w,h]]]:[])]
 const arrow=(from:{x:number;y:number},to:{x:number;y:number})=>{page.line(from,to,{width:.2});const len=Math.hypot(to.x-from.x,to.y-from.y)||1,d={x:(to.x-from.x)/len,y:(to.y-from.y)/len};page.polyline([{x:to.x-d.x*2-d.y,y:to.y-d.y*2+d.x},to,{x:to.x-d.x*2+d.y,y:to.y-d.y*2-d.x}],{width:.2})}
 polygons.forEach((poly,i)=>{const water=roof.waters[i];page.polyline(poly.map(([px,py])=>({x:x+px,y:y+py})),{width:.18},true);const cx=x+poly.reduce((s,p)=>s+p[0],0)/poly.length,cy=y+poly.reduce((s,p)=>s+p[1],0)/poly.length;page.text({x:cx,y:cy-3},water?.displayId??'?',2.5,{align:'center'});if(water?.direction){const d=water.direction==='north'?[0,-1]:water.direction==='south'?[0,1]:water.direction==='west'?[-1,0]:[1,0],length=Math.min(8,w/6,h/6);arrow({x:cx-d[0]*length/2,y:cy+2-d[1]*length/2},{x:cx+d[0]*length/2,y:cy+2+d[1]*length/2})}})
 if(count>=2){page.line({x:x+a,y:y+m},{x:x+b,y:y+m},{width:.4});page.text({x:x+(a+b)/2,y:y+m-3},'Cumeeira (esquema)',2.5,{align:'center'})}
 page.text({x:x+w/2,y:y+h+5},f(roof.lengthM),2.8,{align:'center'});page.text({x:x-5,y:y+h/2},f(roof.widthM),2.8,{rotate:-90,align:'center'})
 let cursor=y+h+14
 for(const water of extent.valid){const high=water.highHeightM!*k,low=water.lowHeightM!*k,projection=water.projectionM!*k,baseline=cursor+high,top={x,y:cursor},end={x:x+projection,y:baseline-low};page.text({x,y:cursor-3},`${water.displayId} — corte/perfil medido`,2.8,{font:'bold'});page.line(top,end,{width:.3});page.polyline([top,{x,y:baseline},{x:x+projection,y:baseline},end],{width:.15,dash:[1,1]});arrow({x:x+projection*.4,y:cursor+(high-low)*.4-2},{x:x+projection*.6,y:cursor+(high-low)*.6-2});page.text({x,y:baseline+4},`Alto ${f(water.highHeightM)} · Baixo ${f(water.lowHeightM)} · Projeção ${f(water.projectionM)}`,2.5);cursor=baseline+18}
 for(const line of extent.details){page.text({x,y:cursor},line,2.7);cursor+=3.5}
 drawTitleBlock(page,{project,floor:project.floors.find(f=>f.id===roof.floorId),title:`${roof.displayId} — ${roof.name}`,option,date,responsible})
 return {page,toPaper,extent}
}
export function roofSheetPdf(input:Parameters<typeof drawRoofSheet>[0]) {const {page}=drawRoofSheet(input);return {bytes:buildPdf(page,`${input.roof.displayId} — ${input.roof.name}`),fileName:`campo-${input.roof.displayId}-${input.option.sheet}-1-${input.option.scale}.pdf`}}
