import { useState } from 'react'
import type { Project, Room, SpatialConnection } from './models'
import { projectRooms } from './relationships'
import { generateId } from './domain'
import { buildPlanRoom, planBounds, worldPoint } from './floorPlan'
import { cornerSnap } from './cornerConnections'

export default function CornerConnectionsPanel({project,room,onChange}:{project:Project;room:Room;onChange:(project:Project)=>void}) {
  const [targetId,setTarget]=useState(''),[sourceId,setSource]=useState(''),[cornerId,setCorner]=useState(''),[face,setFace]=useState<'internal'|'external'>('internal'),[otherFace,setOtherFace]=useState<'internal'|'external'>('internal'),[orientation,setOrientation]=useState<'normal'|'inverted'>('normal')
  const rooms=projectRooms(project).filter(r=>r.id!==room.id && r.floorId===room.floorId),target=rooms.find(r=>r.id===targetId),shape=buildPlanRoom(room),other=target?buildPlanRoom(target):undefined
  const draft:SpatialConnection={id:'preview',type:'corner',a:{roomId:room.id,elementId:sourceId,face},b:{roomId:targetId,elementId:cornerId,face:otherFace},orientation}
  const preview=target?cornerSnap(draft,room,target,{roomId:room.id,floorId:room.floorId,x:0,y:0,rotation:0}):undefined
  const ghost=other&&preview?other.survey.perimeter.segments.map(s=>[worldPoint(s.start,preview),worldPoint(s.end,preview)]):[],bounds=planBounds([...shape.points,...ghost.flat()]),padding=Math.max(bounds.width,bounds.height,.1)*.1
  const links=(project.spatialConnections??[]).filter(c=>c.type==='corner' && (c.a.roomId===room.id || c.b.roomId===room.id))
  return <details className="connection-editor"><summary>Conexões por canto ({links.length})</summary>
    {links.map(c=><div key={c.id}><span>{projectRooms(project).find(r=>r.id===c.a.roomId)?.name} ↔ {projectRooms(project).find(r=>r.id===c.b.roomId)?.name} · {c.orientation==='inverted'?'invertida':'normal'}</span><button onClick={()=>onChange({...project,spatialConnections:project.spatialConnections?.filter(x=>x.id!==c.id),relationships:project.relationships.filter(r=>r.spatialConnectionId!==c.id && r.id!==c.id)})}>Remover conexão</button></div>)}
    <div className="connection-fields"><label>Canto deste ambiente<select value={sourceId} onChange={e=>setSource(e.target.value)}><option value="">Selecionar</option>{shape.survey.perimeter.corners.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Lado deste ambiente<select value={face} onChange={e=>setFace(e.target.value as typeof face)}><option value="internal">Interno</option><option value="external">Externo</option></select></label><label>Outro ambiente<select value={targetId} onChange={e=>{setTarget(e.target.value);setCorner('')}}><option value="">Selecionar</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.displayId} — {r.name}</option>)}</select></label><label>Canto correspondente<select value={cornerId} onChange={e=>setCorner(e.target.value)}><option value="">Selecionar</option>{other?.survey.perimeter.corners.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Lado do outro ambiente<select value={otherFace} onChange={e=>setOtherFace(e.target.value as typeof otherFace)}><option value="internal">Interno</option><option value="external">Externo</option></select></label><label>Orientação<select value={orientation} onChange={e=>setOrientation(e.target.value as typeof orientation)}><option value="normal">Normal — sentidos opostos</option><option value="inverted">Invertida — mesmo sentido</option></select></label></div>
    {preview && <svg className="corner-ghost" style={{width:'100%',height:240}} viewBox={`${bounds.minX-padding} ${bounds.minY-padding} ${bounds.width+2*padding} ${bounds.height+2*padding}`} role="img" aria-label="Prévia fantasma da conexão por canto"><g fill="none" stroke="currentColor" strokeWidth={Math.max(bounds.width,bounds.height)/180}>{shape.survey.perimeter.segments.map(s=><line key={s.wall.id} x1={s.start.x} y1={s.start.y} x2={s.end.x} y2={s.end.y}/>)}<g opacity=".45" strokeDasharray={`${padding/4} ${padding/6}`}>{ghost.map(([a,b],i)=><line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>)}</g></g></svg>}
    <p className="angle-help">Prévia local: tracejado representa o outro ambiente. Confirmar registra o vínculo; aplique o encaixe na Planta Geral para alterar sua posição.</p><button disabled={!preview || links.some(c=>c.a.roomId===room.id && c.a.elementId===sourceId && c.b.roomId===targetId && c.b.elementId===cornerId || c.b.roomId===room.id && c.b.elementId===sourceId && c.a.roomId===targetId && c.a.elementId===cornerId)} onClick={()=>onChange({...project,spatialConnections:[...project.spatialConnections??[],{...draft,id:generateId()}]})}>Confirmar conexão por canto</button>
  </details>
}
