import './floorPlan.css'
import { useState } from 'react'
import type { Project,RoomPlacement } from './models'
import { buildPlanRoom,floorRooms,floorPlacements,insertRoomPlacement,putRoomPlacement,pointDistance,planTolerance } from './floorPlan'
import { assistPlacements,planCompatibility,snapChoices } from './floorPlanConnections'
import FloorPlanCanvas from './FloorPlanCanvas'
import type { PlanVisibility } from './FloorPlanCanvas'
import { MeasurementInput,useMeasurements } from './Measurement'
import { projectChecklistSummary } from './checklist'
function PrecisionControls({placement,onChange}:{placement:RoomPlacement;onChange:(p:RoomPlacement)=>void}) {const [draft,setDraft]=useState(placement),{unit}=useMeasurements(),valid=[draft.x,draft.y,draft.rotation].every(Number.isFinite);return <div className="plan-position"><label>X ({unit})<MeasurementInput value={draft.x} onValue={x=>setDraft({...draft,x:x??NaN})}/></label><label>Y ({unit})<MeasurementInput value={draft.y} onValue={y=>setDraft({...draft,y:y??NaN})}/></label><label>Rotação (°)<input type="number" value={Number.isFinite(draft.rotation)?draft.rotation:''} onChange={e=>setDraft({...draft,rotation:e.target.value===''?NaN:Number(e.target.value)})}/></label><button disabled={!valid} onClick={()=>onChange(draft)}>Aplicar posição</button><button onClick={()=>onChange({...placement,rotation:placement.rotation+45})}>Girar +45°</button><button onClick={()=>onChange({...placement,rotation:placement.rotation-45})}>Girar −45°</button></div>}
export default function FloorPlanPanel({project,floorId,onFloor,onChange,onOpenRoom}:{project:Project;floorId:string;onFloor:(id:string)=>void;onChange:(p:Project)=>void;onOpenRoom:(roomId:string)=>void}) {
 const [selected,setSelected]=useState(''),[focusToken,setFocusToken]=useState(0),[fitToken,setFitToken]=useState(0),[message,setMessage]=useState(''),[visibility,setVisibility]=useState<PlanVisibility>({entry:true,names:true,ids:true,measurements:true,openings:true,objects:true,equipment:true,structural:true})
 const rooms=floorRooms(project,floorId),placements=floorPlacements(project,floorId),placement=placements.find(p=>p.roomId===selected),room=rooms.find(r=>r.id===selected),compatibility=planCompatibility(project,floorId),survey=projectChecklistSummary(project),choices=snapChoices(project,floorId,selected),{format}=useMeasurements()
 function move(p:RoomPlacement){onChange(putRoomPlacement(project,p))}
 function insert(roomId:string){const target=rooms.find(r=>r.id===roomId);if(!target)return;move(insertRoomPlacement(buildPlanRoom(target),placements.map(p=>({placement:p,shape:buildPlanRoom(rooms.find(r=>r.id===p.roomId)!)}))));setSelected(roomId);setFitToken(x=>x+1)}
 function assist(){const result=assistPlacements(project,floorId);let next=project;result.added.forEach(p=>{next=putRoomPlacement(next,p)});if(result.added.length){onChange(next);setFitToken(x=>x+1)}setMessage(!placements.length?'Insira primeiro um ambiente como referência.':`${result.added.length} ambiente(s) posicionado(s). ${result.ambiguous.length?'Há opções ambíguas ou conflitos: selecione o ambiente e escolha o encaixe.':'Os ambientes restantes precisam de montagem manual ou de relações com geometria suficiente.'}`)}
 const labels:Record<keyof PlanVisibility,string>={entry:'Entrada principal / Parede A',names:'Nomes',ids:'IDs',measurements:'Medidas',openings:'Portas/janelas/vãos',objects:'Objetos e móveis',equipment:'Equipamentos',structural:'Vigas/pilares'}
 return <section className="floor-plan"><div className="plan-controls"><div className="editor"><h2>PLANTA GERAL</h2><label>Pavimento<select aria-label="Pavimento da planta geral" value={floorId} onChange={e=>{onFloor(e.target.value);setSelected('');setFitToken(x=>x+1)}}>{!project.floors.length&&<option value="">Sem pavimento</option>}{project.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><div className="plan-progress"><span>Levantamento: <strong>{survey.completeness}%</strong></span><span>Compatibilização: <strong>{compatibility.percentage}%</strong></span></div><p className="muted">Posições em coordenadas reais, exclusivas desta planta. As medidas e os croquis individuais são preservados.</p><button onClick={assist}>Tentar posicionar ambientes relacionados</button>{message&&<p role="status">{message}</p>}</div>
 <section className="editor"><h3>Ambientes disponíveis ({rooms.length})</h3><h4>Ainda não posicionados ({rooms.length-placements.length})</h4>{rooms.filter(r=>!placements.some(p=>p.roomId===r.id)).map(r=><div className={`plan-room-row ${selected===r.id?'active':''}`} key={r.id}><button onClick={()=>setSelected(r.id)}>{r.displayId} — {r.name||'Sem nome'}{r.parentRoomId&&<small> · Subambiente independente</small>}</button><button onClick={()=>insert(r.id)}>Inserir</button></div>)}<h4>Já posicionados ({placements.length})</h4>{rooms.filter(r=>placements.some(p=>p.roomId===r.id)).map(r=><button className={`plan-room-row ${selected===r.id?'active':''}`} key={r.id} onClick={()=>{setSelected(r.id);setFocusToken(x=>x+1)}}>{r.displayId} — {r.name||'Sem nome'}</button>)}</section>
 {room&&<section className="editor"><h3>{room.displayId} — {room.name}</h3>{placement?<><PrecisionControls key={`${placement.roomId}:${placement.x}:${placement.y}:${placement.rotation}`} placement={placement} onChange={move}/><button onClick={()=>setFocusToken(x=>x+1)}>Focar ambiente</button><button onClick={()=>{if(window.confirm('Retirar este ambiente da Planta Geral? Seu croqui e suas medidas serão preservados.'))onChange({...project,roomPlacements:project.roomPlacements?.filter(p=>p.roomId!==selected)})}}>Retirar da planta</button></>:<button onClick={()=>insert(selected)}>Inserir manualmente</button>}<button onClick={()=>onOpenRoom(selected)}>Abrir croqui individual</button><h4>Encaixes pelas relações</h4>{!choices.length&&<p className="muted">Nenhum encaixe disponível. Posicione o ambiente relacionado ou cadastre uma relação. A montagem manual continua disponível.</p>}{choices.length>1&&<p>Mais de uma solução possível. Escolha o elemento, o lado ou a referência de alinhamento.</p>}{choices.map(c=><div className="plan-snap" key={c.id}><span>{c.label}</span>{c.differenceM>planTolerance.lengthM&&<strong>Divergência: {format(c.differenceM)} ({(c.differenceM*100).toLocaleString('pt-BR',{maximumFractionDigits:2})} cm)</strong>}{placement&&pointDistance(placement,c.placement)<=planTolerance.snapM&&<small>Próximo: encaixe disponível</small>}<button onClick={()=>{move(c.placement);setFocusToken(x=>x+1);setMessage('Encaixe aplicado somente à posição e rotação da Planta Geral.')}}>Aplicar encaixe</button></div>)}</section>}
 <details className="editor"><summary>Visibilidade</summary>{(Object.keys(labels) as (keyof PlanVisibility)[]).map(key=><label className="plan-checkbox" key={key}><input type="checkbox" checked={visibility[key]} onChange={e=>setVisibility({...visibility,[key]:e.target.checked})}/>{labels[key]}</label>)}</details>
 <section className="editor"><h3>Alertas de compatibilização ({compatibility.alerts.length})</h3><p className="muted">Estes alertas não alteram a porcentagem do levantamento.</p>{compatibility.alerts.map((a,i)=><button className="plan-alert" key={`${a.roomId}:${i}`} onClick={()=>{setSelected(a.roomId);setFocusToken(x=>x+1)}}><strong>{rooms.find(r=>r.id===a.roomId)?.displayId} {rooms.find(r=>r.id===a.roomId)?.name}{a.otherRoomId&&` ↔ ${rooms.find(r=>r.id===a.otherRoomId)?.name}`}</strong><span>{a.message}</span></button>)}{!compatibility.alerts.length&&<p>Sem alertas de compatibilização neste pavimento.</p>}</section></div><FloorPlanCanvas key={project.id+floorId} project={project} floorId={floorId} placements={placements} selected={selected} onSelect={setSelected} onMove={move} visibility={visibility} focusToken={focusToken} fitToken={fitToken}/></section>
}
