import { bindGridWheel } from './gridWheel'
import { planAnnotationSize } from './planAnnotationScale'
import ArchitecturalDimensionSketch from './ArchitecturalDimensionSketch'
import { layoutDimensions, pointsBox } from './architecturalDimensions'
import { surveyDimensions } from './surveyDimensions'
import { openingSymbol } from './openingSymbols'
import OpeningSymbolSketch from './OpeningSymbolSketch'
import { openingFrame } from './openingFrame'
import { duplicatePlanOpenings } from './planOpeningVisibility'
import { PlanLabelLayoutContext } from './PlanLabel'
import PlanLabel from './PlanLabel'
import type { PlanLabelControls } from './PlanLabel'
import { lineRotation } from './labelRotation'
import { wallPlanningValue, transformAssembly } from './planAssembly'
import type { AssemblyPick } from './planAssembly'
import PlanEntryMarker from './PlanEntryMarker'
import { columnProfilePoints } from './structural'
import { useCallback,useEffect,useMemo,useRef,useState } from 'react'
import type { PointerEvent as ReactPointerEvent } from 'react'
import type { Project,RoomPlacement,SpatialSide } from './models'
import { buildPlanRoom,floorRooms,worldPoint,planBounds } from './floorPlan'
import { sharedPlanFaces } from './floorPlanFaces'
import { useMeasurements } from './Measurement'
export interface PlanVisibility {entry?:boolean;names:boolean;ids:boolean;measurements:boolean;openings:boolean;objects:boolean;equipment:boolean;structural:boolean}
export default function FloorPlanCanvas({project,floorId,placements,selected,onSelect,onMove,visibility,focusToken,fitToken,labelControls,pickedFeatures,previewRoomIds,moving=true,groupIds,gridVisible=false,gridStep=.1,snap,onFeature}:{project:Project;floorId:string;placements:RoomPlacement[];selected:string;onSelect:(id:string)=>void;onMove:(p:RoomPlacement)=>void;visibility:PlanVisibility;focusToken:number;fitToken:number;labelControls?:(roomId:string)=>PlanLabelControls;pickedFeatures?:SpatialSide[];previewRoomIds?:Set<string>;moving?:boolean;groupIds?:Set<string>;gridVisible?:boolean;gridStep?:number;snap?:(p:RoomPlacement)=>RoomPlacement;onFeature?:(p:AssemblyPick)=>void}) {
 const svg=useRef<SVGSVGElement>(null),[camera,setCamera]=useState({x:-1,y:-1,width:12,height:9}),[draft,setDraft]=useState<RoomPlacement>(),[expanded,setExpanded]=useState(false),{format}=useMeasurements()
 const displayed=draft&&groupIds?.has(draft.roomId)?transformAssembly(placements,placements.find(p=>p.roomId===draft.roomId)!,draft,groupIds):placements
 const shapes=useMemo(()=>floorRooms(project,floorId).map(buildPlanRoom),[project,floorId]),shown=useMemo(()=>displayed.map(p=>({shape:shapes.find(s=>s.room.id===p.roomId)!,placement:draft?.roomId===p.roomId?draft:p})).filter(x=>x.shape),[displayed,shapes,draft]),effective=useMemo(()=>shown.map(x=>x.placement),[shown]),shared=useMemo(()=>sharedPlanFaces(project,floorId,effective),[project,floorId,effective])
 const gesture=useRef<{start:{x:number;y:number};screen:{x:number;y:number};camera:typeof camera;placement?:RoomPlacement;pinch?:{distance:number;mid:{x:number;y:number}}}|undefined>(undefined),pointers=useRef(new Map<number,{x:number;y:number}>()),draftRef=useRef<RoomPlacement|undefined>(undefined);draftRef.current=draft
 function fit(roomId?:string){const points=shown.filter(x=>!roomId||x.placement.roomId===roomId).flatMap(({shape,placement})=>shape.points.map(p=>worldPoint(p,placement))),b=planBounds(points),aspect=(svg.current?.clientWidth??800)/(svg.current?.clientHeight??600);let width=Math.max(2,b.width+1),height=Math.max(2,b.height+1);if(width/height<aspect)width=height*aspect;else height=width/aspect;setCamera({x:(b.minX+b.maxX-width)/2,y:(b.minY+b.maxY-height)/2,width,height})}
 useEffect(()=>{fit()},[fitToken,floorId]) // Visual camera only.
 useEffect(()=>{if(focusToken)fit(selected)},[focusToken])
 useEffect(()=>{const el=svg.current;if(!el)return;const resize=new ResizeObserver(()=>setCamera(c=>{const aspect=Math.max(1,el.clientWidth)/Math.max(1,el.clientHeight),width=Math.max(c.width,c.height*aspect),height=width/aspect;return {x:c.x+(c.width-width)/2,y:c.y+(c.height-height)/2,width,height}}));resize.observe(el);return()=>resize.disconnect()},[])
 const point=(x:number,y:number)=>{const matrix=svg.current!.getScreenCTM()!.inverse();return new DOMPoint(x,y).matrixTransform(matrix)}
 function zoom(factor:number,clientX?:number,clientY?:number){const rect=svg.current!.getBoundingClientRect(),rx=clientX==null?.5:(clientX-rect.left)/rect.width,ry=clientY==null?.5:(clientY-rect.top)/rect.height;setCamera(c=>{const width=Math.max(.3,Math.min(5000,c.width*factor)),ratio=width/c.width,height=c.height*ratio;return {x:c.x+rx*(c.width-width),y:c.y+ry*(c.height-height),width,height}})}
 const bindSvg=useCallback((node:SVGSVGElement|null)=>{
  svg.current=node
  if(!node)return
  const release=bindGridWheel(node,event=>{if(event.deltaY&&!gesture.current)zoom(event.deltaY>0?1.1:.9,event.clientX,event.clientY)})
  return ()=>{release();if(svg.current===node)svg.current=null}
 },[])
 function down(e:ReactPointerEvent<SVGSVGElement>){if(e.button!==0)return;const p=point(e.clientX,e.clientY),target=(e.target as Element).closest('[data-room-id]')?.getAttribute('data-room-id')??undefined,placement=moving&&!onFeature&&!e.shiftKey&&target?effective.find(x=>x.roomId===target):undefined;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId)
 if(pointers.current.size===2){const [a,b]=[...pointers.current.values()];setDraft(undefined);draftRef.current=undefined;gesture.current={start:p,screen:{x:e.clientX,y:e.clientY},camera,pinch:{distance:Math.hypot(a.x-b.x,a.y-b.y),mid:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}};return}
 if(target&&!onFeature)onSelect(target);if(onFeature&&target){const feature=(e.target as Element).closest('[data-feature-id]');if(feature){const id=feature.getAttribute('data-feature-id')!,wallId=feature.getAttribute('data-corner-wall')??undefined;onFeature({roomId:target,elementId:id,wallId})}return}gesture.current={start:p,screen:{x:e.clientX,y:e.clientY},camera,placement}
 }
 function move(e:ReactPointerEvent<SVGSVGElement>){if(!pointers.current.has(e.pointerId)||!gesture.current)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture.current,rect=e.currentTarget.getBoundingClientRect()
 if(g.pinch&&pointers.current.size===2){const [a,b]=[...pointers.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y)||1,ratio=Math.max(.3/g.camera.width,Math.min(5000/g.camera.width,g.pinch.distance/distance)),width=g.camera.width*ratio,height=g.camera.height*ratio,mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},ax=g.camera.x+(g.pinch.mid.x-rect.left)/rect.width*g.camera.width,ay=g.camera.y+(g.pinch.mid.y-rect.top)/rect.height*g.camera.height;setCamera({x:ax-(mid.x-rect.left)/rect.width*width,y:ay-(mid.y-rect.top)/rect.height*height,width,height});return}
 if(g.pinch)return
 const dx=(e.clientX-g.screen.x)/rect.width*g.camera.width,dy=(e.clientY-g.screen.y)/rect.height*g.camera.height
 if(g.placement){if(Math.hypot(e.clientX-g.screen.x,e.clientY-g.screen.y)<4)return;const raw={...g.placement,x:g.placement.x+dx,y:g.placement.y+dy},next=snap?snap(raw):raw;draftRef.current=next;setDraft(next)}else setCamera({...g.camera,x:g.camera.x-dx,y:g.camera.y-dy})
 }
 function up(e:ReactPointerEvent<SVGSVGElement>,cancel=false){pointers.current.delete(e.pointerId);if(!pointers.current.size){if(!cancel&&draftRef.current)onMove(draftRef.current);gesture.current=undefined;setDraft(undefined);draftRef.current=undefined}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 const suppressedOpenings=useMemo(()=>duplicatePlanOpenings(project,floorId,effective),[project,floorId,effective])
 const chosen=(roomId:string,id:string)=>pickedFeatures?.some(s=>s.roomId===roomId&&(s.elementId===id||s.wallId===id))??false
 const font=planAnnotationSize(shown.map(x=>x.shape)),line=(a:{x:number;y:number},b:{x:number;y:number},key:string,roomId:string,selectedWall=false)=><line key={key} x1={a.x} y1={a.y} x2={b.x} y2={b.y} data-room-id={roomId} vectorEffect="non-scaling-stroke" stroke={selected===roomId?'var(--plan-selected)':'var(--plan-line)'} strokeWidth={selectedWall?3:2}/>
 const dimensionSource=surveyDimensions(shown,font,format),dimensions=layoutDimensions(dimensionSource.requests.map(r=>{const [roomId,key]=r.key.split('|'),adopted=key.startsWith('wall:')?wallPlanningValue(project,roomId,key.slice(5)):undefined;const text=[visibility.ids?r.text.split(' · ')[0]:'',visibility.measurements?r.text.split(' · ').slice(1).join(' · '):''].filter(Boolean).join(' · ');return {...r,text:adopted==null?text:`${text} [ref. ${format(adopted)}]`}}),dimensionSource.obstacles,font*.85)
 return <aside className={`floor-plan-canvas ${expanded?'expanded':''}`}><div className="plan-canvas-tools"><strong>Planta Geral</strong><button onClick={()=>zoom(.75)} aria-label="Ampliar planta">＋</button><button onClick={()=>zoom(1.33)} aria-label="Reduzir planta">−</button><button onClick={()=>fit()}>Ajustar todos</button><button className="plan-expand" onClick={()=>{setExpanded(!expanded);gesture.current=undefined}}> {expanded?'Recolher':'Expandir'}</button></div><PlanLabelLayoutContext.Provider value={[...shown.flatMap(({shape,placement})=>[...shape.faces.values(),...shape.internalFaces.values()].flat().map(f=>pointsBox([worldPoint(f.start,placement),worldPoint(f.end,placement)],font*.12))),...[...dimensions.values()].map(d=>d.box)]}><svg ref={bindSvg} role="img" aria-label="Planta geral interativa do pavimento" viewBox={`${camera.x} ${camera.y} ${camera.width} ${camera.height}`} onPointerDown={down} onPointerMove={move} onPointerUp={e=>up(e)} onPointerCancel={e=>up(e,true)}>
 <defs><pattern id={`plan-grid-${floorId}`} width={Math.max(gridStep,camera.width/100)} height={Math.max(gridStep,camera.width/100)} patternUnits="userSpaceOnUse"><path d={`M ${Math.max(gridStep,camera.width/100)} 0 L 0 0 0 ${Math.max(gridStep,camera.width/100)}`} fill="none" stroke="var(--plan-line)" opacity=".12" strokeWidth={camera.width/1500}/></pattern></defs>{gridVisible&&<rect x={camera.x} y={camera.y} width={camera.width} height={camera.height} fill={`url(#plan-grid-${floorId})`} pointerEvents="none"/>}
 {shown.map(({shape,placement})=>{const room=shape.room,bounds=planBounds(shape.polygon),center=worldPoint({x:(bounds.minX+bounds.maxX)/2,y:(bounds.minY+bounds.maxY)/2},placement);return <g key={room.id} data-room-id={room.id} opacity={previewRoomIds?.has(room.id)?.48:1}><polygon points={shape.polygon.map(p=>{const w=worldPoint(p,placement);return `${w.x},${w.y}`}).join(' ')} fill={selected===room.id?'var(--plan-fill)':'transparent'} stroke="none"/><circle cx={center.x} cy={center.y} r={font*1.5} fill="transparent"/>{[...shape.faces].flatMap(([id,faces])=>shared.suppressed.has(`${room.id}:${id}`)?[]:faces.map((f,i)=>line(worldPoint(f.start,placement),worldPoint(f.end,placement),`${id}:${i}`,room.id)))}{[...shape.internalFaces].flatMap(([id,faces])=>faces.map((f,i)=>line(worldPoint(f.start,placement),worldPoint(f.end,placement),`${id}:${i}`,room.id)))}
 {(visibility.ids||visibility.names)&&<PlanLabel id="room" x={center.x} y={center.y} size={Math.min(font*1.1,Math.max(.025,Math.min(bounds.width,bounds.height)/12))} controls={labelControls?.(room.id)}>{visibility.ids&&room.displayId}<tspan x={center.x} dy={font*1.4}>{visibility.names&&room.name}</tspan></PlanLabel>}
 {onFeature&&<g>{shape.survey.perimeter.segments.map(s=>{const a=worldPoint(s.start,placement),b=worldPoint(s.end,placement);return <line key={s.wall.id} data-feature-id={s.wall.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={chosen(room.id,s.wall.id)?'var(--plan-selected)':'transparent'} strokeOpacity={.55} strokeWidth={chosen(room.id,s.wall.id)?6:16} vectorEffect="non-scaling-stroke"/>})}{shape.survey.perimeter.corners.map(c=>{const p=worldPoint(c.position,placement);return <g key={c.id} data-feature-id={c.id} data-corner-wall={c.wallIds[0]}><circle cx={p.x} cy={p.y} r={font*(chosen(room.id,c.id)?1:.65)} fill={chosen(room.id,c.id)?'var(--plan-selected)':'var(--surface)'} stroke="var(--plan-selected)" strokeWidth={2} vectorEffect="non-scaling-stroke"/><text x={p.x+font} y={p.y+font} fontSize={font} fill="var(--plan-text)">{c.label}</text></g>})}</g>}
 {visibility.entry!==false&&<PlanEntryMarker shape={shape} placement={placement} size={font*.8}/>}
 {(visibility.measurements||visibility.ids)&&shape.survey.perimeter.segments.map(s=>{const dimension=dimensions.get(`${room.id}|wall:${s.wall.id}`);return dimension&&<ArchitecturalDimensionSketch key={s.wall.id} dimension={dimension} font={font*.85} showLines={visibility.measurements} plan planControls={labelControls?.(room.id)}/>})}

 {visibility.openings&&shape.survey.openings.placements.filter(o=>onFeature||!suppressedOpenings.has(`${room.id}:${o.opening.id}`)).map(o=>{const a=worldPoint(o.start,placement),b=worldPoint(o.end,placement),hide=suppressedOpenings.has(`${room.id}:${o.opening.id}`);return <g key={o.opening.id} data-feature-id={o.opening.id}>{onFeature&&<line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={chosen(room.id,o.opening.id)?'var(--plan-selected)':'transparent'} strokeOpacity={.55} strokeWidth={chosen(room.id,o.opening.id)?6:20} vectorEffect="non-scaling-stroke"/>}{!hide&&<><OpeningSymbolSketch parts={openingSymbol(o.opening,o.start,o.end,openingFrame(shape.survey.perimeter,o,room.wallMeasurementFace),project.representationMode)} project={p=>worldPoint(p,placement)}/><PlanLabel id={`opening:${o.opening.id}`} x={(a.x+b.x)/2} y={(a.y+b.y)/2+font} size={font*.8} angle={lineRotation(a,b)} controls={labelControls?.(room.id)}>{o.opening.label}{visibility.measurements&&` · ${format(o.opening.widthM,false)} × ${format(o.opening.heightM)}`}</PlanLabel></>}</g>})}
 {(visibility.measurements||visibility.ids)&&shape.survey.internalWalls.placements.map(pi=>{const d=dimensions.get(`${room.id}|internal:${pi.internalWall.id}`);return d&&<ArchitecturalDimensionSketch key={pi.internalWall.id} dimension={d} font={font*.85} showLines={visibility.measurements} plan planControls={labelControls?.(room.id)}/>})}

 {/* Object sizes are canonical meters; placement adds translation and rotation only. */}
 {shape.objects.filter(o=>o.object.category==='structural'?visibility.structural:o.object.category==='equipment'?visibility.equipment:visibility.objects).map(o=>{const c=worldPoint(o.center,placement),profile=o.object.structuralKind==='column'?columnProfilePoints(o.object.profile,o.widthM,o.heightM,o.object.dimensions.webM??0,o.object.dimensions.flangeM??0):undefined;return <g key={o.object.id}><g transform={`translate(${c.x} ${c.y}) rotate(${placement.rotation+(o.object.rotationDegrees??0)})`} fill="none" stroke="var(--plan-object)" strokeWidth={1.5} vectorEffect="non-scaling-stroke">{profile?<polygon vectorEffect="non-scaling-stroke" points={profile.map(p=>p.join(',')).join(' ')}/>:o.object.shape==='circle'?<circle vectorEffect="non-scaling-stroke" r={o.widthM/2}/>:o.object.shape==='line'?<line vectorEffect="non-scaling-stroke" x1={-o.widthM/2} x2={o.widthM/2}/>:<rect vectorEffect="non-scaling-stroke" x={-o.widthM/2} y={-o.heightM/2} width={o.widthM} height={o.heightM}/>}</g><PlanLabel id={`object:${o.object.id}`} x={c.x} y={c.y} size={font*.8} angle={placement.rotation+(o.object.rotationDegrees??0)} controls={labelControls?.(room.id)}>{visibility.ids&&o.object.displayId}</PlanLabel></g>})}
 </g>})}{shared.faces.flatMap((s,i)=>s.ranges.map((f,j)=>line(f.start,f.end,`shared:${i}:${j}`,s.roomId,true)))}
 </svg></PlanLabelLayoutContext.Provider><small>{onFeature?'Clique na referência para encaixar.':moving?'Arraste o ambiente para mover.':'Selecione Mover para deslocar ambientes.'} Arraste o fundo para navegar. Dois dedos: zoom. Shift + arrastar: navegar.{[...dimensions.values()].some(d=>d.conflict)&&' Há cotas sem posição livre: ajuste os rótulos ou inverta o lado.'}</small></aside>
}
