import AssemblyChangeNotice from './AssemblyChangeNotice'
import './floorPlan.css'
import { useEffect,useState } from 'react'
import type { Project,RoomPlacement,SpatialConnection,WallCompatibility,PlanPreferences } from './models'
import { buildPlanRoom,floorRooms,floorPlacements,insertRoomPlacement,putRoomPlacement } from './floorPlan'
import { assistPlacements,planCompatibility } from './floorPlanConnections'
import { connectedAssembly,snapPlacement,transformAssembly } from './planAssembly'
import type { AssemblyPick } from './planAssembly'
import FloorPlanCanvas from './FloorPlanCanvas'
import type { PlanVisibility } from './FloorPlanCanvas'
import PlanFitPanel from './PlanFitPanel'
import { MeasurementInput,useMeasurements } from './Measurement'
import { mapProjectRooms } from './spatialConnections'
import { projectChecklistSummary } from './checklist'
const defaultVisibility:PlanVisibility={entry:true,names:true,ids:true,measurements:true,openings:true,objects:true,equipment:true,structural:true}
function PrecisionControls({placement,onChange}:{placement:RoomPlacement;onChange:(p:RoomPlacement)=>void}) {const [draft,setDraft]=useState(placement),{unit}=useMeasurements();return <div className="plan-position"><label>X ({unit})<MeasurementInput value={draft.x} onValue={x=>setDraft({...draft,x:x??NaN})}/></label><label>Y ({unit})<MeasurementInput value={draft.y} onValue={y=>setDraft({...draft,y:y??NaN})}/></label><label>Rotação (°)<input type="number" value={Number.isFinite(draft.rotation)?draft.rotation:''} onChange={e=>setDraft({...draft,rotation:e.target.value===''?NaN:Number(e.target.value)})}/></label><button disabled={![draft.x,draft.y,draft.rotation].every(Number.isFinite)} onClick={()=>onChange(draft)}>Aplicar posição</button></div>}
export default function FloorPlanPanel({project,floorId,onFloor,onChange,onOpenRoom}:{project:Project;floorId:string;onFloor:(id:string)=>void;onChange:(p:Project)=>void;onOpenRoom:(roomId:string)=>void}) {
 const [selected,setSelected]=useState(''),[focusToken,setFocusToken]=useState(0),[fitToken,setFitToken]=useState(0),[message,setMessage]=useState(''),[adding,setAdding]=useState(false),[fitting,setFitting]=useState(false),[moving,setMoving]=useState(false),[fullscreen,setFullscreen]=useState(false),[preview,setPreview]=useState<RoomPlacement>(),[previewConnection,setPreviewConnection]=useState<SpatialConnection>(),[pickSide,setPickSide]=useState<'a'|'b'>('a'),[pick,setPick]=useState<{side:'a'|'b';value:AssemblyPick}>(),[pendingMove,setPendingMove]=useState<RoomPlacement>(),[arrangeLabels,setArrangeLabels]=useState(false),[activeLabel,setActiveLabel]=useState<{roomId:string;key:string}>(),[groupMode,setGroupMode]=useState(false),[history,setHistory]=useState<Project[]>([])
 const preferences=project.planPreferences?.[floorId]??{},visibility={...defaultVisibility,...preferences.visibility} as PlanVisibility,rooms=floorRooms(project,floorId),placements=floorPlacements(project,floorId),placement=placements.find(p=>p.roomId===selected),room=rooms.find(r=>r.id===selected),compatibility=planCompatibility(project,floorId),survey=projectChecklistSummary(project),{format}=useMeasurements()
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFullscreen(false);setFitting(false);setPreview(undefined);setPreviewConnection(undefined)}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[])
 function commit(next:Project){setHistory(h=>[...h.slice(-29),project]);onChange(next)}
 function prefs(next:PlanPreferences){commit({...project,planPreferences:{...project.planPreferences,[floorId]:{...preferences,...next}}})}
 function changeLabel(roomId:string,key:string,value:{dx:number;dy:number;rotation?:number;side?:1|-1}|undefined){commit(mapProjectRooms(project,r=>{if(r.id!==roomId)return r;const offsets={...r.planLabelOffsets};if(value)offsets[key]=value;else delete offsets[key];return {...r,planLabelOffsets:offsets}}))}
 function choose(id:string){if(id!==selected&&!(groupMode&&connectedAssembly(project,selected).has(id)))setGroupMode(false);setSelected(id)}
 function insert(roomId:string){const target=rooms.find(r=>r.id===roomId);if(!target)return;const p=insertRoomPlacement(buildPlanRoom(target),placements.map(p=>({placement:p,shape:buildPlanRoom(rooms.find(r=>r.id===p.roomId)!)})));let next=putRoomPlacement(project,{...p,locked:!placements.length});if(!placements.length)next={...next,planPreferences:{...project.planPreferences,[floorId]:{...preferences,baseRoomId:roomId}}};commit(next);choose(roomId);setAdding(false);setFitToken(x=>x+1)}
 function applyMove(p:RoomPlacement,group:boolean,detach=false){const before=placements.find(x=>x.roomId===p.roomId);if(!before)return;const ids=group?connectedAssembly(project,p.roomId):new Set([p.roomId]);if(group&&placements.some(x=>ids.has(x.roomId)&&x.locked)){setMessage('Destrave os ambientes travados do conjunto antes de movê-lo.');return}let next={...project,roomPlacements:transformAssembly(project.roomPlacements??[],before,{...p,locked:detach?false:p.locked},ids)};if(detach){next={...next,roomPlacements:next.roomPlacements.map(x=>x.roomId===p.roomId?{...x,locked:false}:x),spatialConnections:next.spatialConnections?.map(c=>[c.a.roomId,c.b.roomId].includes(p.roomId)?{...c,assemblyLocked:false}:c)}}commit(next);setPendingMove(undefined)}
 function move(p:RoomPlacement){if(preferences.locked){setMessage('Planta TRAVADA. Ative Editar/Destravar para reposicionar.');return}const before=placements.find(x=>x.roomId===p.roomId);if(!before)return;if(Math.abs(p.x-before.x)+Math.abs(p.y-before.y)+Math.abs(p.rotation-before.rotation)<1e-9)return;const ids=connectedAssembly(project,p.roomId);if(before.locked||ids.size>1&&!groupMode){setPendingMove(p);return}applyMove(p,groupMode)}
 function confirm(c:SpatialConnection,p:RoomPlacement,compat?:WallCompatibility){const existing=placements.find(x=>x.roomId===p.roomId),fixedId=c.a.roomId===p.roomId?c.b.roomId:c.a.roomId,ids=connectedAssembly(project,p.roomId,fixedId);if(existing?.locked){setMessage('Destrave o ambiente móvel antes de confirmar o encaixe.');return}if(existing&&[...ids].some(id=>id!==p.roomId&&placements.find(x=>x.roomId===id)?.locked)){setMessage('O ambiente móvel pertence a um conjunto travado. Destrave-o antes de encaixar.');return}let next=existing?{...project,roomPlacements:transformAssembly(project.roomPlacements??[],existing,p,ids)}:putRoomPlacement(project,p);next={...next,spatialConnections:[...(next.spatialConnections??[]).filter(x=>x.id!==c.id),c],wallCompatibilities:compat?[...(next.wallCompatibilities??[]).filter(x=>x.connectionId!==c.id),compat]:next.wallCompatibilities};if(c.type==='opening')next=mapProjectRooms(next,r=>({...r,openings:r.openings.map(o=>{const side=[c.a,c.b].find(s=>s.roomId===r.id&&s.elementId===o.id);if(!side)return o;const other=side===c.a?c.b:c.a;return {...o,connectedRoomId:other.roomId,connectedOpeningId:other.elementId}})}));commit(next);choose(p.roomId);setFitting(false);setPreview(undefined);setPreviewConnection(undefined);setMessage('Encaixe confirmado. O conjunto está protegido e as medidas originais foram preservadas.')}
 const previewIds=preview&&previewConnection?connectedAssembly(project,preview.roomId,previewConnection?(previewConnection.a.roomId===preview.roomId?previewConnection.b.roomId:previewConnection.a.roomId):undefined):new Set<string>(preview?[preview.roomId]:[]),previewBefore=preview&&placements.find(p=>p.roomId===preview.roomId),shown=preview?(previewBefore?transformAssembly(placements,previewBefore,preview,previewIds):[...placements,preview]):placements
 const labels:Record<keyof PlanVisibility,string>={entry:'Entrada principal / Parede A',names:'Nomes',ids:'IDs',measurements:'Medidas',openings:'Portas/janelas/vãos',objects:'Objetos e móveis',equipment:'Equipamentos',structural:'Vigas/pilares'}
 return <section className={`floor-plan plan-assembly ${fullscreen?'plan-fullscreen':''}`}><header className="plan-main-toolbar"><button onClick={()=>{setAdding(v=>!v);setFitting(false);setPreview(undefined)}}>+ Ambiente</button><button disabled={!placements.length} onClick={()=>{setFitting(v=>!v);setPick(undefined);setPickSide('a');setAdding(false);setMoving(false);setPreview(undefined)}}>Encaixar</button><button aria-pressed={moving} onClick={()=>{if(preferences.locked){prefs({locked:false});setMoving(true)}else setMoving(v=>!v);setFitting(false);setPreview(undefined);setPreviewConnection(undefined)}}>{preferences.locked?'TRAVADO · Editar/Destravar':'Mover'}</button><button disabled={!history.length} onClick={()=>{const previous=history.at(-1)!;onChange(previous);setHistory(h=>h.slice(0,-1));setPreview(undefined);setFitting(false)}}>Desfazer</button><button onClick={()=>setFitToken(v=>v+1)}>Ajustar vista</button></header><AssemblyChangeNotice project={project} onChange={commit}/><div className="plan-controls"><section className="editor"><div className="plan-section-heading"><h2>PLANTA GERAL</h2><button aria-label={fullscreen?'Sair da tela cheia':'Tela cheia'} onClick={()=>setFullscreen(v=>!v)}>{fullscreen?'Sair da tela cheia':'Tela cheia'}</button></div><label>Pavimento<select aria-label="Pavimento da planta geral" value={floorId} onChange={e=>{onFloor(e.target.value);choose('');setFitting(false);setPreview(undefined)}}>{project.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><div className="plan-progress"><span>Levantamento: <strong>{survey.completeness}%</strong></span><span>Compatibilização: <strong>{compatibility.percentage}%</strong></span></div><label>Ambiente base<select aria-label="Ambiente base" value={preferences.baseRoomId??''} onChange={e=>{const id=e.target.value;commit({...project,roomPlacements:project.roomPlacements?.map(p=>p.roomId===id?{...p,locked:true}:p),planPreferences:{...project.planPreferences,[floorId]:{...preferences,baseRoomId:id||undefined}}})}}><option value="">Escolher base</option>{rooms.filter(r=>placements.some(p=>p.roomId===r.id)).map(r=><option key={r.id} value={r.id}>{r.displayId} — {r.name}</option>)}</select></label>{message&&<p role="status">{message}</p>}</section>
 {adding&&<section className="editor"><h3>Inserir ambiente</h3>{rooms.filter(r=>!placements.some(p=>p.roomId===r.id)).map(r=><button className="plan-room-row" key={r.id} onClick={()=>insert(r.id)}>{r.displayId} — {r.name} · Inserir</button>)}{rooms.length===placements.length&&<p>Todos os ambientes estão posicionados. Novos ambientes podem ser criados na árvore ou durante o vínculo no croqui.</p>}</section>}
 {fitting&&<PlanFitPanel key={floorId} project={project} floorId={floorId} selected={selected} pick={pick} onPick={setPickSide} onPreview={(p,c)=>{setPreview(p);setPreviewConnection(c)}} onConfirm={confirm} onCancel={()=>{setFitting(false);setPreview(undefined);setPreviewConnection(undefined)}}/>}
 <details className="editor" open={!fitting}><summary>Ambientes · {placements.length}/{rooms.length} posicionados</summary>{rooms.map(r=><div className={`plan-room-row ${selected===r.id?'active':''}`} key={r.id}><button onClick={()=>{choose(r.id);if(placements.some(p=>p.roomId===r.id))setFocusToken(v=>v+1)}}>{r.displayId} — {r.name}{preferences.baseRoomId===r.id?' · Base':''}{placements.find(p=>p.roomId===r.id)?.locked?' 🔒':''}{!placements.some(p=>p.roomId===r.id)?' · Não posicionado':''}</button>{!placements.some(p=>p.roomId===r.id)&&<button onClick={()=>insert(r.id)}>Inserir</button>}</div>)}</details>
 {room&&placement&&!fitting&&<section className="editor"><h3>{room.displayId} — {room.name}</h3><div className="plan-context-actions"><button onClick={()=>commit(putRoomPlacement(project,{...placement,locked:!placement.locked}))}>{placement.locked?'Destravar':'Travar'}</button><button onClick={()=>move({...placement,rotation:placement.rotation+45})}>Girar +45°</button><button aria-pressed={groupMode} onClick={()=>{setGroupMode(v=>!v);setMoving(true)}}>Mover conjunto</button><button onClick={()=>{if(window.confirm('Desvincular somente a montagem deste ambiente? Medidas e relações do levantamento serão preservadas.'))commit({...project,spatialConnections:project.spatialConnections?.map(c=>[c.a.roomId,c.b.roomId].includes(selected)?{...c,assemblyDetached:true,assemblyLocked:false}:c)})}}>Desvincular montagem</button></div><details><summary>Posição precisa</summary><PrecisionControls key={`${placement.x}:${placement.y}:${placement.rotation}`} placement={placement} onChange={move}/></details><button onClick={()=>onOpenRoom(selected)}>Abrir croqui individual</button><button onClick={()=>{if(window.confirm('Retirar da planta sem apagar o levantamento?'))commit({...project,roomPlacements:project.roomPlacements?.filter(p=>p.roomId!==selected),planPreferences:{...project.planPreferences,[floorId]:{...preferences,baseRoomId:preferences.baseRoomId===selected?undefined:preferences.baseRoomId}}})}}>Retirar da planta</button></section>}
 <details className="editor"><summary>Opções de montagem e camadas</summary><label className="plan-checkbox"><input type="checkbox" checked={!!preferences.locked} onChange={e=>{prefs({locked:e.target.checked});setMoving(false)}}/>TRAVADO — proteger montagem</label><button aria-pressed={arrangeLabels} onClick={()=>{setArrangeLabels(v=>!v);setMoving(false)}}>Ajustar rótulos</button>{arrangeLabels&&activeLabel&&<div>{/^(wall|internal):/.test(activeLabel.key)?<button onClick={()=>{const saved=rooms.find(r=>r.id===activeLabel.roomId)?.planLabelOffsets?.[activeLabel.key]??{dx:0,dy:0};changeLabel(activeLabel.roomId,activeLabel.key,{...saved,side:saved.side===-1?1:-1})}}>Inverter lado da cota</button>:<label>Girar rótulo (°)<input type="number" step="5" placeholder="Automático" value={rooms.find(r=>r.id===activeLabel.roomId)?.planLabelOffsets?.[activeLabel.key]?.rotation??''} onChange={e=>changeLabel(activeLabel.roomId,activeLabel.key,{...rooms.find(r=>r.id===activeLabel.roomId)?.planLabelOffsets?.[activeLabel.key]??{dx:0,dy:0},rotation:e.target.value===''?undefined:Number(e.target.value)})}/></label>}<button onClick={()=>changeLabel(activeLabel.roomId,activeLabel.key,undefined)}>Restaurar automático</button></div>}<button onClick={()=>{const result=assistPlacements(project,floorId);if(result.added.length){commit({...project,roomPlacements:[...project.roomPlacements??[],...result.added]});setFitToken(v=>v+1)}setMessage(!placements.length?'Insira primeiro o ambiente base.':`${result.added.length} ambiente(s) inserido(s). ${result.ambiguous.length?'Há encaixes ambíguos: use Encaixar e escolha visualmente.':'Ambientes existentes mantiveram suas posições.'}`)}}>Tentar posicionar ambientes relacionados</button><label className="plan-checkbox"><input type="checkbox" checked={preferences.snap!==false} onChange={e=>prefs({snap:e.target.checked})}/>Encaixe automático ao mover</label><label className="plan-checkbox"><input type="checkbox" checked={preferences.gridVisible!==false} onChange={e=>prefs({gridVisible:e.target.checked})}/>Mostrar grid</label><label>Passo do grid<MeasurementInput value={preferences.gridStepM??.1} onValue={v=>{if(v&&v>0)prefs({gridStepM:v})}}/></label>{(Object.keys(labels) as (keyof PlanVisibility)[]).map(key=><label className="plan-checkbox" key={key}><input type="checkbox" checked={!!visibility[key]} onChange={e=>prefs({visibility:{...visibility,[key]:e.target.checked}})}/>{labels[key]}</label>)}</details>
 {!!project.wallCompatibilities?.length&&<details className="editor"><summary>Medidas compatibilizadas</summary>{project.wallCompatibilities.map(c=><div key={c.id}><p>{rooms.find(r=>r.id===c.a.roomId)?.name} ↔ {rooms.find(r=>r.id===c.b.roomId)?.name}: {c.strategy==='original'?'originais':format(c.valueM)}</p><button onClick={()=>commit({...project,wallCompatibilities:project.wallCompatibilities?.filter(x=>x.id!==c.id)})}>Restaurar valores originais</button></div>)}</details>}
 <details className="editor"><summary>Alertas de compatibilização ({compatibility.alerts.length})</summary>{compatibility.alerts.map((a,i)=><button className="plan-alert" key={i} onClick={()=>{choose(a.roomId);setFocusToken(v=>v+1)}}>{rooms.find(r=>r.id===a.roomId)?.name} · {a.message}</button>)}</details></div>
 <FloorPlanCanvas key={project.id+floorId} project={project} floorId={floorId} placements={shown} selected={selected} onSelect={choose} onMove={move} visibility={visibility} focusToken={focusToken} fitToken={fitToken} previewRoomIds={previewIds} moving={moving&&!preferences.locked&&!fitting&&!arrangeLabels} groupIds={groupMode?connectedAssembly(project,selected):undefined} labelControls={id=>({enabled:arrangeLabels,offsets:rooms.find(r=>r.id===id)?.planLabelOffsets,onSelect:key=>setActiveLabel({roomId:id,key}),onChange:(key,value)=>changeLabel(id,key,value)})} pickedFeatures={fitting&&previewConnection?[previewConnection.a,previewConnection.b]:undefined} gridVisible={preferences.gridVisible!==false} gridStep={preferences.gridStepM??.1} snap={p=>preferences.snap===false?p:snapPlacement(project,p,preferences.gridStepM??.1,groupMode?connectedAssembly(project,p.roomId):undefined)} onFeature={fitting?(value)=>setPick({side:pickSide,value}):undefined}/>
 {pendingMove&&<div className="plan-dialog-backdrop"><section className="editor plan-dialog" role="dialog" aria-modal="true" aria-label="Mover ambiente protegido"><h3>Montagem protegida</h3><p>Este ambiente está travado ou faz parte de um conjunto conectado.</p>{placements.some(p=>connectedAssembly(project,pendingMove.roomId).has(p.roomId)&&p.locked)&&<p>Para mover o conjunto, destrave primeiro a base e os demais ambientes travados.</p>}<button disabled={placements.some(p=>connectedAssembly(project,pendingMove.roomId).has(p.roomId)&&p.locked)} onClick={()=>applyMove(pendingMove,true)}>Mover conjunto</button><button onClick={()=>applyMove(pendingMove,false,true)}>Desbloquear e mover apenas este</button><button onClick={()=>setPendingMove(undefined)}>Cancelar</button></section></div>}
 </section>
}
