import { doorDrawing } from './openings'
import { columnProfilePoints } from './structural'
import { useEffect,useMemo,useRef,useState } from 'react'
import type { PointerEvent as ReactPointerEvent } from 'react'
import type { Project,RoomPlacement } from './models'
import { buildPlanRoom,floorRooms,worldPoint,planBounds } from './floorPlan'
import { sharedPlanFaces } from './floorPlanFaces'
import { useMeasurements } from './Measurement'
export interface PlanVisibility {names:boolean;ids:boolean;measurements:boolean;openings:boolean;objects:boolean;equipment:boolean;structural:boolean}
export default function FloorPlanCanvas({project,floorId,placements,selected,onSelect,onMove,visibility,focusToken,fitToken}:{project:Project;floorId:string;placements:RoomPlacement[];selected:string;onSelect:(id:string)=>void;onMove:(p:RoomPlacement)=>void;visibility:PlanVisibility;focusToken:number;fitToken:number}) {
 const svg=useRef<SVGSVGElement>(null),[camera,setCamera]=useState({x:-1,y:-1,width:12,height:9}),[draft,setDraft]=useState<RoomPlacement>(),[expanded,setExpanded]=useState(false),{format}=useMeasurements()
 const shapes=useMemo(()=>floorRooms(project,floorId).map(buildPlanRoom),[project,floorId]),shown=useMemo(()=>placements.map(p=>({shape:shapes.find(s=>s.room.id===p.roomId)!,placement:draft?.roomId===p.roomId?draft:p})).filter(x=>x.shape),[placements,shapes,draft]),effective=useMemo(()=>shown.map(x=>x.placement),[shown]),shared=useMemo(()=>sharedPlanFaces(project,floorId,effective),[project,floorId,effective])
 const gesture=useRef<{start:{x:number;y:number};screen:{x:number;y:number};camera:typeof camera;placement?:RoomPlacement;pinch?:{distance:number;mid:{x:number;y:number}}}|undefined>(undefined),pointers=useRef(new Map<number,{x:number;y:number}>()),draftRef=useRef<RoomPlacement|undefined>(undefined);draftRef.current=draft
 function fit(roomId?:string){const points=shown.filter(x=>!roomId||x.placement.roomId===roomId).flatMap(({shape,placement})=>shape.points.map(p=>worldPoint(p,placement))),b=planBounds(points),aspect=(svg.current?.clientWidth??800)/(svg.current?.clientHeight??600);let width=Math.max(2,b.width+1),height=Math.max(2,b.height+1);if(width/height<aspect)width=height*aspect;else height=width/aspect;setCamera({x:(b.minX+b.maxX-width)/2,y:(b.minY+b.maxY-height)/2,width,height})}
 useEffect(()=>{fit()},[fitToken,floorId,expanded]) // Visual camera only.
 useEffect(()=>{if(focusToken)fit(selected)},[focusToken])
 useEffect(()=>{const el=svg.current;if(!el)return;const resize=new ResizeObserver(()=>setCamera(c=>{const aspect=Math.max(1,el.clientWidth)/Math.max(1,el.clientHeight),width=Math.max(c.width,c.height*aspect),height=width/aspect;return {x:c.x+(c.width-width)/2,y:c.y+(c.height-height)/2,width,height}}));resize.observe(el);return()=>resize.disconnect()},[])
 const point=(x:number,y:number)=>{const matrix=svg.current!.getScreenCTM()!.inverse();return new DOMPoint(x,y).matrixTransform(matrix)}
 function zoom(factor:number,clientX?:number,clientY?:number){const rect=svg.current!.getBoundingClientRect(),rx=clientX==null?.5:(clientX-rect.left)/rect.width,ry=clientY==null?.5:(clientY-rect.top)/rect.height;setCamera(c=>{const width=Math.max(.3,Math.min(5000,c.width*factor)),ratio=width/c.width,height=c.height*ratio;return {x:c.x+rx*(c.width-width),y:c.y+ry*(c.height-height),width,height}})}
 function down(e:ReactPointerEvent<SVGSVGElement>){if(e.button!==0)return;const p=point(e.clientX,e.clientY),target=(e.target as Element).closest('[data-room-id]')?.getAttribute('data-room-id')??undefined,placement=!e.shiftKey&&target?effective.find(x=>x.roomId===target):undefined;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId)
 if(pointers.current.size===2){const [a,b]=[...pointers.current.values()];setDraft(undefined);draftRef.current=undefined;gesture.current={start:p,screen:{x:e.clientX,y:e.clientY},camera,pinch:{distance:Math.hypot(a.x-b.x,a.y-b.y),mid:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}};return}
 if(target)onSelect(target);gesture.current={start:p,screen:{x:e.clientX,y:e.clientY},camera,placement}
 }
 function move(e:ReactPointerEvent<SVGSVGElement>){if(!pointers.current.has(e.pointerId)||!gesture.current)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture.current,rect=e.currentTarget.getBoundingClientRect()
 if(g.pinch&&pointers.current.size===2){const [a,b]=[...pointers.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y)||1,ratio=Math.max(.3/g.camera.width,Math.min(5000/g.camera.width,g.pinch.distance/distance)),width=g.camera.width*ratio,height=g.camera.height*ratio,mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},ax=g.camera.x+(g.pinch.mid.x-rect.left)/rect.width*g.camera.width,ay=g.camera.y+(g.pinch.mid.y-rect.top)/rect.height*g.camera.height;setCamera({x:ax-(mid.x-rect.left)/rect.width*width,y:ay-(mid.y-rect.top)/rect.height*height,width,height});return}
 if(g.pinch)return
 const dx=(e.clientX-g.screen.x)/rect.width*g.camera.width,dy=(e.clientY-g.screen.y)/rect.height*g.camera.height
 if(g.placement){const next={...g.placement,x:g.placement.x+dx,y:g.placement.y+dy};draftRef.current=next;setDraft(next)}else setCamera({...g.camera,x:g.camera.x-dx,y:g.camera.y-dy})
 }
 function up(e:ReactPointerEvent<SVGSVGElement>,cancel=false){pointers.current.delete(e.pointerId);if(!pointers.current.size){if(!cancel&&draftRef.current)onMove(draftRef.current);gesture.current=undefined;setDraft(undefined);draftRef.current=undefined}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 const font=camera.width/Math.max(1,svg.current?.clientWidth??800)*12,line=(a:{x:number;y:number},b:{x:number;y:number},key:string,roomId:string,selectedWall=false)=><line key={key} x1={a.x} y1={a.y} x2={b.x} y2={b.y} data-room-id={roomId} vectorEffect="non-scaling-stroke" stroke={selected===roomId?'var(--plan-selected)':'var(--plan-line)'} strokeWidth={selectedWall?3:2}/>
 return <aside className={`floor-plan-canvas ${expanded?'expanded':''}`}><div className="plan-canvas-tools"><strong>Planta Geral</strong><button onClick={()=>zoom(.75)} aria-label="Ampliar planta">＋</button><button onClick={()=>zoom(1.33)} aria-label="Reduzir planta">−</button><button onClick={()=>fit()}>Ajustar todos</button><button className="plan-expand" onClick={()=>{setExpanded(!expanded);gesture.current=undefined}}> {expanded?'Recolher':'Expandir'}</button></div><svg ref={svg} role="img" aria-label="Planta geral interativa do pavimento" viewBox={`${camera.x} ${camera.y} ${camera.width} ${camera.height}`} onPointerDown={down} onPointerMove={move} onPointerUp={e=>up(e)} onPointerCancel={e=>up(e,true)} onWheel={e=>{if(!gesture.current)zoom(e.deltaY>0?1.1:.9,e.clientX,e.clientY)}}>
 {shown.map(({shape,placement})=>{const room=shape.room,bounds=planBounds(shape.polygon),center=worldPoint({x:(bounds.minX+bounds.maxX)/2,y:(bounds.minY+bounds.maxY)/2},placement);return <g key={room.id} data-room-id={room.id}><polygon points={shape.polygon.map(p=>{const w=worldPoint(p,placement);return `${w.x},${w.y}`}).join(' ')} fill={selected===room.id?'var(--plan-fill)':'transparent'} stroke="none"/><circle cx={center.x} cy={center.y} r={font*1.5} fill="transparent"/>{[...shape.faces].flatMap(([id,faces])=>shared.suppressed.has(`${room.id}:${id}`)?[]:faces.map((f,i)=>line(worldPoint(f.start,placement),worldPoint(f.end,placement),`${id}:${i}`,room.id)))}{[...shape.internalFaces].flatMap(([id,faces])=>faces.map((f,i)=>line(worldPoint(f.start,placement),worldPoint(f.end,placement),`${id}:${i}`,room.id)))}
 {(visibility.ids||visibility.names)&&<text x={center.x} y={center.y} fontSize={font*1.1} textAnchor="middle" fill="var(--plan-text)">{visibility.ids&&room.displayId}<tspan x={center.x} dy={font*1.4}>{visibility.names&&room.name}</tspan></text>}
 {visibility.measurements&&shape.survey.perimeter.segments.map(s=>{const p=worldPoint({x:(s.start.x+s.end.x)/2,y:(s.start.y+s.end.y)/2},placement);return <text key={s.wall.id} x={p.x} y={p.y-font*.6} fontSize={font*.85} textAnchor="middle" fill="var(--plan-text)">{s.wall.label} · {format(s.wall.lengthM)}</text>})}
 {visibility.openings&&shape.survey.openings.placements.map(o=>{const a=worldPoint(o.start,placement),b=worldPoint(o.end,placement),length=Math.hypot(b.x-a.x,b.y-a.y),direction={x:(b.x-a.x)/length,y:(b.y-a.y)/length},door=o.opening.doorKind!=='sliding'?doorDrawing(o.opening,a,b,direction):null;return <g key={o.opening.id}>{door?<>{line(door.leaf[0],door.leaf[1],o.opening.id,room.id)}<path d={door.arc} fill="none" stroke="var(--plan-line)" strokeWidth={1} vectorEffect="non-scaling-stroke"/></>:o.opening.type==='window'?<line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="var(--plan-object)" strokeDasharray="4 3" strokeWidth={1} vectorEffect="non-scaling-stroke"/>:o.opening.doorKind==='sliding'?<line x1={a.x-direction.y*.025} y1={a.y+direction.x*.025} x2={b.x-direction.y*.025} y2={b.y+direction.x*.025} stroke="var(--plan-object)" strokeWidth={1} vectorEffect="non-scaling-stroke"/>:null}<text x={(a.x+b.x)/2} y={(a.y+b.y)/2+font} fontSize={font*.8} textAnchor="middle" fill="var(--plan-text)">{o.opening.label}</text></g>})}
 {/* Object sizes are canonical meters; placement adds translation and rotation only. */}
 {shape.objects.filter(o=>o.object.category==='structural'?visibility.structural:o.object.category==='equipment'?visibility.equipment:visibility.objects).map(o=>{const c=worldPoint(o.center,placement),profile=o.object.structuralKind==='column'?columnProfilePoints(o.object.profile,o.widthM,o.heightM,o.object.dimensions.webM??0,o.object.dimensions.flangeM??0):undefined;return <g key={o.object.id} transform={`translate(${c.x} ${c.y}) rotate(${placement.rotation+(o.object.rotationDegrees??0)})`} fill="none" stroke="var(--plan-object)" strokeWidth={1.5} vectorEffect="non-scaling-stroke">{profile?<polygon points={profile.map(p=>p.join(',')).join(' ')}/>:o.object.shape==='circle'?<circle r={o.widthM/2}/>:o.object.shape==='line'?<line x1={-o.widthM/2} x2={o.widthM/2}/>:<rect x={-o.widthM/2} y={-o.heightM/2} width={o.widthM} height={o.heightM}/>}<text fontSize={font*.8} textAnchor="middle" fill="var(--plan-text)" stroke="none">{visibility.ids&&o.object.displayId}</text></g>})}
 </g>})}{shared.faces.flatMap((s,i)=>s.ranges.map((f,j)=>line(f.start,f.end,`shared:${i}:${j}`,s.roomId,true)))}
 </svg><small>Arraste o ambiente para mover. Arraste o fundo para navegar. Dois dedos: zoom. Shift + arrastar: navegar.</small></aside>
}
