import { useState } from 'react'
import type { Room,SurveyPlacement } from './models'
import type { RoomGeometry } from './roomGeometry'
import { circleIntersections,distance,positiveLength } from './surveySolver'
import { getCorners } from './corners'
import { id,wallLabel } from './domain'
import { nextWallIndex } from './deletions'
import { MeasurementInput,useMeasurements } from './Measurement'
export default function NextWallPanel({room,survey,onChange,onClose,closing=false}:{room:Room;survey:RoomGeometry;onChange:(r:Room)=>void;onClose:()=>void;closing?:boolean}) {
 const {unit,format}=useMeasurements(),[length,setLength]=useState<number|null>(null),[method,setMethod]=useState<SurveyPlacement['method']>(closing?'closure':room.walls.length?'diagonal':'orthogonal'),[reference,setReference]=useState('origin'),[diagonal,setDiagonal]=useState<number|null>(null),[angle,setAngle]=useState<number|null>(90),[side,setSide]=useState<1|-1|undefined>(),[wallId]=useState(id),[diagonalId]=useState(id),label=wallLabel(nextWallIndex(room)),segments=survey.perimeter.segments,start=segments.at(-1)?.end??{x:0,y:0},known=[{id:'origin',point:{x:0,y:0},label:'Início de A'},...segments.slice(0,-1).map((s,i)=>({id:s.wall.id,point:s.end,label:`Canto ${s.wall.label}${room.walls[i+1]?.label??''}`}))],ref=known.find(p=>p.id===reference),lastDirection=segments.at(-1)?.direction??{x:1,y:0}
 let candidates:{x:number;y:number}[]=[]
 if(positiveLength(length)){if(method==='diagonal'&&ref&&positiveLength(diagonal))candidates=circleIntersections(start,length,ref.point,diagonal);else if(method!=='diagonal'){const heading=method==='closure'?Math.atan2(-start.y,-start.x):room.walls.length?Math.atan2(lastDirection.y,lastDirection.x)+(180-(method==='orthogonal'?90:angle??90))*Math.PI/180:0;candidates=[{x:start.x+Math.cos(heading)*length,y:start.y+Math.sin(heading)*length}]}}
 const chosen=candidates.length===1?1:side,valid=positiveLength(length)&&!!candidates.length&&!!chosen&&(method!=='angle'||positiveLength(angle)&&angle<360)
 const points=[{x:0,y:0},...segments.flatMap(s=>[s.start,s.end]),...candidates],minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),scale=Math.min(260/Math.max(maxX-minX,.1),150/Math.max(maxY-minY,.1)),at=(p:{x:number;y:number})=>({x:160+(p.x-(minX+maxX)/2)*scale,y:105+(p.y-(minY+maxY)/2)*scale})
 function save(){
  if(!valid)return
  const placement:SurveyPlacement={method,...method==='diagonal'?{referenceVertexId:reference,diagonalId,side:chosen}:method==='angle'?{angleDegrees:angle!}:{}}
  const wall={id:wallId,label,lengthM:length,thickness:.15,surveyPlacement:placement},walls=[...room.walls,wall],origin=getCorners(room.walls,room.corners).at(-1)
  const activeCorners=getCorners(walls,room.corners).map((c,i)=>{if(i===walls.length-1&&origin)return {...origin,wallIds:c.wallIds};return room.corners.find(s=>s.id===c.id)??{...c,angleSource:method==='angle'&&c.wallIds[1]===wall.id?'informed' as const:method==='orthogonal'?'assumed' as const:'calculated' as const,angleDegrees:method==='angle'&&c.wallIds[1]===wall.id?angle:method==='orthogonal'?90:null}})
  const corners=[...room.corners.filter(c=>!activeCorners.some(a=>a.id===c.id)),...activeCorners]
  onChange({...room,walls,corners,perimeterClosed:method==='closure',diagonals:method==='diagonal'?[...room.diagonals,{id:diagonalId,cornerIds:[reference,wallId],vertexIds:[reference,wallId],lengthM:diagonal,source:'measured',checkOnly:false}]:room.diagonals})
  onClose()
 }

 return <section className="next-wall-panel"><div className="section-top"><h3>Próxima parede · {label}</h3><button onClick={onClose}>Cancelar</button></div><label>Comprimento medido da parede {label} ({unit})<MeasurementInput autoFocus value={length} onValue={v=>{setLength(v);setSide(undefined)}}/></label>{room.walls.length>0&&<label>Posicionar por<select value={method} onChange={e=>{setMethod(e.target.value as SurveyPlacement['method']);setSide(undefined)}}><option value="diagonal">Diagonal — recomendado</option><option value="orthogonal">90°</option><option value="angle">Ângulo medido entre paredes</option><option value="closure">Fechamento até o início de A</option></select></label>}{method==='diagonal'&&<><label>Canto conhecido de referência<select value={reference} onChange={e=>{setReference(e.target.value);setSide(undefined)}}>{known.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Diagonal medida até a ponta da nova parede ({unit})<MeasurementInput value={diagonal} onValue={v=>{setDiagonal(v);setSide(undefined)}}/></label></>}{method==='angle'&&<label>Ângulo interno medido (°)<input type="number" min="0" max="360" step=".1" value={angle??''} onChange={e=>setAngle(e.target.value===''?null:Number(e.target.value))}/><small>Use o ângulo entre as duas paredes. Um canto reentrante pode ser maior que 180°.</small></label>}{method==='closure'&&<p>Distância restante até o início: {format(distance(start,{x:0,y:0}))}. Digite o comprimento medido; diferenças continuarão visíveis.</p>}
 <svg viewBox="0 0 320 210" role="img" aria-label="Prévia das posições da próxima parede">{segments.map(s=>{const a=at(s.start),b=at(s.end);return <line key={s.wall.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="currentColor" strokeWidth="2"/>})}{candidates.map((p,i)=>{const a=at(start),b=at(p),r=ref&&at(ref.point);return <g key={i} role="button" tabIndex={0} aria-label={`Escolher posição ${i+1}`} onClick={()=>setSide(i===0?1:-1)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSide(i===0?1:-1)}}}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={chosen===(i===0?1:-1)?'#c18a00':'#4774a5'} strokeWidth="5" strokeDasharray="6 4"/>{method==='diagonal'&&r&&<line x1={r.x} y1={r.y} x2={b.x} y2={b.y} stroke="#4774a5" strokeDasharray="3 4"/>}<circle cx={b.x} cy={b.y} r="10" fill={chosen===(i===0?1:-1)?'#f2c94c':'#d9e1ea'}/><text x={b.x} y={b.y+4} textAnchor="middle" fontSize="12" fill="#16202b">{i+1}</text></g>})}</svg>{candidates.length>1&&<p>Clique na posição 1 ou 2 que corresponde à obra.</p>}{method==='diagonal'&&positiveLength(length)&&positiveLength(diagonal)&&!candidates.length&&<p role="alert">Estas distâncias não localizam um vértice. Confira as medidas ou escolha outro canto.</p>}<button className="primary" disabled={!valid} onClick={save}>{method==='closure'?'Fechar perímetro':`Registrar parede ${label}`}</button></section>
}
