import { parallelOffset } from './architecturalDimensions'
import { createContext,useContext,isValidElement,useId,useRef,useState } from 'react'
import type { ReactNode } from 'react'
import type { LabelOffsets } from './models'
import { readableRotation } from './labelRotation'
type Box={key?:string;x:number;y:number;width:number;height:number}
export const PlanLabelLayoutContext=createContext<Box[]|undefined>(undefined)
function labelText(node:ReactNode):string {return typeof node==='string'||typeof node==='number'?String(node):Array.isArray(node)?node.map(labelText).join(' '):isValidElement<{children?:ReactNode}>(node)?labelText(node.props.children):''}
export interface PlanLabelControls {enabled?:boolean;offsets?:LabelOffsets;onSelect?:(key:string)=>void;onChange?:(key:string,value:{dx:number;dy:number;rotation?:number;side?:1|-1})=>void}
export default function PlanLabel({id,x,y,angle=0,size,children,controls,dimension=false}:{id:string;x:number;y:number;angle?:number;size:number;children:ReactNode;controls?:PlanLabelControls;dimension?:boolean}) {
 const saved=controls?.offsets?.[id]??{dx:0,dy:0},[live,setLive]=useState<typeof saved>(),session=useRef<{pointer:number;x:number;y:number;scale:number;offset:typeof saved}|undefined>(undefined),rawOffset=live??saved,offset=dimension?{...rawOffset,...parallelOffset(rawOffset,angle),rotation:undefined}:rawOffset
 const boxId=useId(),occupied=useContext(PlanLabelLayoutContext),rotation=readableRotation(offset.rotation??angle),r=rotation*Math.PI/180,text=labelText(children),width=Math.max(size,text.length*size*.55),height=size*(id==='room'?2.7:1.5),bw=Math.abs(width*Math.cos(r))+Math.abs(height*Math.sin(r)),bh=Math.abs(width*Math.sin(r))+Math.abs(height*Math.cos(r))
 const candidates=dimension?[{dx:0,dy:0}]:controls?.offsets?.[id]?[{dx:0,dy:0}]:[{dx:0,dy:0},...[2.5,-2.5,4.5,-4.5,7,-7,10,-10].map(v=>({dx:-Math.sin(r)*size*v,dy:Math.cos(r)*size*v}))]
 const box=(p:{dx:number;dy:number})=>({key:boxId,x:x+offset.dx+p.dx-bw/2,y:y+offset.dy+p.dy-size,width:bw,height:bh})
 const score=(b:Box)=>(occupied??[]).filter(a=>a.key!==boxId).reduce((s,a)=>s+Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)),0)
 const automatic=candidates.reduce((best,p)=>score(box(p))<score(box(best))?p:best,candidates[0]);if(text&&occupied){const existing=occupied.findIndex(b=>b.key===boxId);if(existing>=0)occupied[existing]=box(automatic);else occupied.push(box(automatic))}
 return <g transform={`translate(${offset.dx+automatic.dx} ${offset.dy+automatic.dy}) rotate(${readableRotation(offset.rotation??angle)} ${x} ${y})`}><text x={x} y={y} fontSize={size} textAnchor="middle" fill="var(--plan-text)" style={{fontSize:size,pointerEvents:controls?.enabled?'auto':'none',cursor:controls?.enabled?'move':undefined}} onPointerDown={e=>{if(!controls?.enabled)return;e.stopPropagation();const matrix=e.currentTarget.ownerSVGElement?.getScreenCTM();session.current={pointer:e.pointerId,x:e.clientX,y:e.clientY,scale:matrix?.a?1/matrix.a:1,offset:saved};e.currentTarget.setPointerCapture(e.pointerId);controls.onSelect?.(id)}} onPointerMove={e=>{const s=session.current;if(!s||s.pointer!==e.pointerId)return;e.stopPropagation();{const change={dx:s.offset.dx+(e.clientX-s.x)*s.scale,dy:s.offset.dy+(e.clientY-s.y)*s.scale};setLive({...s.offset,...dimension?parallelOffset(change,angle):change})}}} onPointerUp={e=>{if(!session.current)return;e.stopPropagation();if(live)controls?.onChange?.(id,live);session.current=undefined;setLive(undefined)}} onPointerCancel={()=>{session.current=undefined;setLive(undefined)}}>{children}</text></g>
}
