import type { Roof } from './models'
import { roofSlope,roofDirections } from './roofs'
import { useMeasurements } from './Measurement'
import { useId,useState } from 'react'
const number=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:1})
export default function RoofSketch({roof}:{roof:Roof}) {
  const [expanded,setExpanded]=useState(false)
  const {format}=useMeasurements(),id=useId().replace(/:/g,'')
  const measured=roof.lengthM!=null&&roof.lengthM>0&&Number.isFinite(roof.lengthM)&&roof.widthM!=null&&roof.widthM>0&&Number.isFinite(roof.widthM)
  const scale=measured?Math.min(300/roof.lengthM!,180/roof.widthM!):1,w=measured?roof.lengthM!*scale:280,h=measured?roof.widthM!*scale:160,x=(400-w)/2,y=(260-h)/2
  const count=roof.waterCount,m=h/2,a=count===4?w*.25:0,b=count===4?w*.75:count===3?w*.75:w
  const polygons:number[][][]=count===1?[[[0,0],[w,0],[w,h],[0,h]]]:[[[0,0],[w,0],[b,m],[a,m]],[[0,h],[w,h],[b,m],[a,m]],...(count===4?[[[0,0],[a,m],[0,h]]]:[]),...(count>=3?[[[w,0],[b,m],[w,h]]]:[])]
  return <aside className={`roof-sketch ${expanded?'expanded':''}`}><button className="roof-expand" onClick={()=>setExpanded(v=>!v)}>{expanded?'Recolher':'Expandir'}</button><h3>{roof.displayId} — vista superior</h3><svg viewBox="0 0 400 300" role="img" aria-label={`Vista superior de ${roof.name}, ${count} águas`}><defs><marker id={id} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="currentColor"/></marker></defs>
    {polygons.map((points,index)=>{const water=roof.waters[index];const cx=x+points.reduce((sum,p)=>sum+p[0],0)/points.length,cy=y+points.reduce((sum,p)=>sum+p[1],0)/points.length;const direction=water?.direction || (count===1?'south':index===0?'north':index===1?'south':count===4&&index===2?'west':'east');const vector=direction==='north'?[0,-1]:direction==='south'?[0,1]:direction==='west'?[-1,0]:[1,0];return <g key={water?.id ?? index}><polygon points={points.map(p=>`${x+p[0]},${y+p[1]}`).join(' ')} fill="none" stroke="currentColor"/><text x={cx} y={cy-10} textAnchor="middle">{water?.displayId}</text>{direction && <line x1={cx-vector[0]*8} y1={cy-vector[1]*8+5} x2={cx+vector[0]*20} y2={cy+vector[1]*20+5} stroke="currentColor" strokeDasharray={water?.direction?undefined:'3 3'} markerEnd={`url(#${id})`}><title>{water?.direction?roofDirections[water.direction]:'Caimento ilustrativo: sentido ainda não definido'}</title></line>}</g>})}
    {count>=2 && <><line x1={x+a} y1={y+m} x2={x+b} y2={y+m} stroke="currentColor" strokeWidth="2"/><text x={x+(a+b)/2} y={y+m-5} textAnchor="middle">Cumeeira</text></>}
    <text x="200" y={y+h+24} textAnchor="middle">{format(roof.lengthM)}</text><text x={x-8} y={y+h/2} textAnchor="middle" transform={`rotate(-90 ${x-8} ${y+h/2})`}>{format(roof.widthM)}</text>
  </svg>{!measured && <p>Esquema provisório: informe as dimensões. O caimento de cada água é configurável.</p>}
    {roof.waters.some(w=>!w.direction) && <p>Setas tracejadas: caimentos ilustrativos ainda não confirmados.</p>}<details className="roof-profiles"><summary>Corte / perfil auxiliar (opcional)</summary>{roof.waterCount===2 && <svg viewBox="0 0 400 130" role="img" aria-label="Cumeeira e dois caimentos"><path d="M40 95L200 25L360 95" fill="none" stroke="currentColor" strokeWidth="2"/><line x1="180" y1="45" x2="90" y2="84" stroke="currentColor" markerEnd={`url(#${id})`}/><line x1="220" y1="45" x2="310" y2="84" stroke="currentColor" markerEnd={`url(#${id})`}/><text x="200" y="18" textAnchor="middle">Cumeeira — esquema</text>{roof.waters.map((water,i)=><text key={water.id} x={i===0?90:310} y="118" textAnchor="middle">{water.displayId} {roofSlope(water)?`≈ ${number(roofSlope(water)!.percent)}%`:'Inclinação pendente'}</text>)}</svg>}
    {roof.waters.map(water=>{const slope=roofSlope(water);const high=water.highHeightM,low=water.lowHeightM,proj=water.projectionM;const valid=slope && high!=null&&low!=null&&proj!=null && [high,low,proj].every(Number.isFinite) && proj>0 && high>=low && low>=0;const s=valid?Math.min(260/proj!,100/Math.max(high!,.01)):1;const end=valid?60+proj!*s:320,top=valid?170-high!*s:50,bottom=valid?170-low!*s:100;return <div key={water.id}><h4>{water.displayId} — {water.direction?roofDirections[water.direction]:'Sentido pendente'}</h4><svg viewBox="0 0 400 235" role="img" aria-label={`Perfil ${water.displayId}`}><line x1="60" y1={top} x2={end} y2={bottom} stroke="currentColor" strokeWidth="2"/><path d={`M60 ${top}V170H${end}V${bottom}`} fill="none" stroke="currentColor" strokeDasharray="4 3"/><text x="60" y={top-12}>Alto: {water.highSide || '?'}</text><text x="60" y="188">{format(high)}</text><text x={end} y={bottom-12} textAnchor="end">Baixo: {water.lowSide || '?'}</text><text x={end} y="188" textAnchor="end">{format(low)}</text><text x="200" y="210" textAnchor="middle">Projeção: {format(proj)}</text></svg><p>{slope?`Desnível: ${format(slope.riseM)} · Inclinação: ≈ ${number(slope.percent)}% · ≈ ${number(slope.degrees)}°`:'Dados insuficientes ou alturas/projeção inválidas. Perfil ilustrativo.'}</p></div>})}
    </details>
  </aside>
}
