import { useEffect,useState,useRef } from 'react'
import type { Photo,Project,Roof } from './models'
import { createRoof,nextRoofSequence,changeWaterCount,roofChecklist,roofSlope,roofDirections } from './roofs'
import { MeasurementInput,useMeasurements } from './Measurement'
import RoofSketch from './RoofSketch'
import PhotoOffer from './PhotoOffer'
import { Thumbnail,FullPhoto } from './PhotoPanel'
import { queuePhotoDeletion } from './photoStorage'
export default function RoofsPanel({project,onChange,initialRoofId}:{project:Project;onChange:(project:Project)=>void;initialRoofId?:string}) {
  const {unit,format}=useMeasurements(),[selected,setSelected]=useState(initialRoofId ?? project.roofs?.[0]?.id),[offer,setOffer]=useState<string>(),[deleting,setDeleting]=useState<string>(),[deletingPhoto,setDeletingPhoto]=useState<string>(),[view,setView]=useState<Photo>(),[countRequest,setCountRequest]=useState<1|2|3|4>()
  useEffect(()=>{if(initialRoofId)setSelected(initialRoofId)},[initialRoofId])
  const latest=useRef(project);latest.current=project
  const roof=project.roofs?.find(r=>r.id===selected) ?? project.roofs?.[0]
  const change=(changes:Partial<Roof>)=>roof && onChange({...project,roofs:(project.roofs ?? []).map(r=>r.id===roof.id?{...r,...changes}:r)})
  const add=()=>{const next=createRoof(project);onChange({...project,roofs:[...project.roofs ?? [],next],roofCounter:nextRoofSequence(project)});setSelected(next.id);setOffer(next.id)}
  const photoCard=(photo:Photo,owner?:Roof)=><article key={photo.id} className="photo-card"><button onClick={()=>setView(photo)} aria-label={`Abrir foto ${photo.originalFileName}`}><Thumbnail photo={photo}/></button><p>{photo.originalFileName}</p><button onClick={()=>setDeletingPhoto(photo.id)}>Excluir foto</button>{deletingPhoto===photo.id && <div role="alertdialog" aria-label="Excluir foto?"><button onClick={()=>setDeletingPhoto(undefined)}>Cancelar</button><button onClick={()=>{queuePhotoDeletion(photo.fileId);onChange({...project,roofs:(project.roofs ?? []).map(r=>r.id===owner?.id?{...r,photos:r.photos?.filter(p=>p.id!==photo.id)}:r),detachedRoofPhotos:project.detachedRoofPhotos?.filter(p=>p.id!==photo.id)});setDeletingPhoto(undefined)}}>Confirmar exclusão</button></div>}</article>
  return <section className="editor roofs-panel" aria-label="Telhados do projeto"><span className="eyebrow">MÓDULO INDEPENDENTE</span><h2>Telhados</h2><p>Águas e inclinações são medidas separadamente. As imagens são opcionais.</p><button onClick={add}>＋ Novo telhado</button>{project.roofs?.length? <label>Telhado<select value={roof?.id} onChange={e=>{setSelected(e.target.value);setCountRequest(undefined);setOffer(undefined)}}>{project.roofs.map(r=><option key={r.id} value={r.id}>{r.displayId} — {r.name}</option>)}</select></label>:<p>Nenhum telhado cadastrado.</p>}
    {roof && <div className="roof-workspace"><div><h3>{roof.displayId} — cadastro</h3><div className="object-fields"><label>Nome<input value={roof.name} onChange={e=>change({name:e.target.value})}/></label><label>Pavimento<select value={roof.floorId ?? ''} onChange={e=>change({floorId:e.target.value || undefined})}><option value="">Projeto / sem pavimento</option>{project.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Forma<select value={roof.shape} onChange={e=>change({shape:e.target.value as Roof['shape']})}><option value="rectangular">Retangular</option><option value="square">Quadrada</option></select></label><label>Comprimento ({unit})<MeasurementInput value={roof.lengthM} onValue={v=>change({lengthM:v})}/></label><label>Largura ({unit})<MeasurementInput value={roof.widthM} onValue={v=>change({widthM:v})}/></label><label>Quantidade de águas<select value={roof.waterCount} onChange={e=>{const count=Number(e.target.value) as Roof['waterCount'];if(count<roof.waterCount)setCountRequest(count);else change(changeWaterCount(roof,count))}}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>Observação<textarea value={roof.note ?? ''} onChange={e=>change({note:e.target.value})}/></label></div>
      {roof.shape==='square' && roof.lengthM!==roof.widthM && <p role="status">Forma quadrada: confira os lados. As medidas informadas foram preservadas.</p>}{countRequest && <div role="alertdialog" aria-label="Reduzir águas?"><p>Reduzir para {countRequest} águas remove os dados das águas excedentes.</p><button onClick={()=>setCountRequest(undefined)}>Cancelar</button><button onClick={()=>{change(changeWaterCount(roof,countRequest));setCountRequest(undefined)}}>Confirmar redução</button></div>}
      {roof.waters.map((water,index)=>{const update=(changes:Partial<typeof water>)=>change({waters:roof.waters.map(w=>w.id===water.id?{...w,...changes}:w)}),slope=roofSlope(water);return <details key={water.id} open><summary>{water.displayId} — água {index+1}</summary><div className="object-fields"><label>Inclinação informada (%)<input type="number" min="0" step="any" inputMode="decimal" value={water.inclinationPercent ?? ''} onChange={e=>update({inclinationPercent:e.target.value===''?null:Number(e.target.value)})}/></label><label>Sentido do caimento<select value={water.direction} onChange={e=>update({direction:e.target.value as typeof water.direction})}><option value="">Ainda não definido</option>{Object.entries(roofDirections).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><details><summary>Alturas e cálculo auxiliar (opcional)</summary><div className="object-fields"><label>Lado/ponto mais alto<input value={water.highSide} onChange={e=>update({highSide:e.target.value})}/></label><label>Altura maior ({unit})<MeasurementInput value={water.highHeightM} onValue={v=>update({highHeightM:v})}/></label><label>Lado/ponto mais baixo<input value={water.lowSide} onChange={e=>update({lowSide:e.target.value})}/></label><label>Altura menor ({unit})<MeasurementInput value={water.lowHeightM} onValue={v=>update({lowHeightM:v})}/></label><label>Projeção horizontal ({unit})<MeasurementInput value={water.projectionM} onValue={v=>update({projectionM:v})}/></label></div></details><p>{slope?`Desnível ${format(slope.riseM)} · ≈ ${slope.percent.toLocaleString('pt-BR',{maximumFractionDigits:1})}% · ≈ ${slope.degrees.toLocaleString('pt-BR',{maximumFractionDigits:1})}°`:'Informe a inclinação desta água. Alturas e projeção são opcionais.'}</p></details>})}
      <h3>Checklist do telhado — {roofChecklist(roof).completeness}%</h3><ul className="roof-checklist">{roofChecklist(roof).checks.map(c=><li key={c.key}><span>{c.completed?'✓':'⚠'} {c.label}</span><label><input type="checkbox" checked={roof.checks?.[c.key]?.status==='na'} onChange={e=>change({checks:{...roof.checks,[c.key]:{status:e.target.checked?'na':'pending'}}})}/> Não aplicável</label></li>)}</ul>
      <h3>Fotos vinculadas: {roof.photos?.length ?? 0}</h3><button onClick={()=>setOffer(roof.id)}>📷 Tirar foto / importar</button><div className="photo-grid">{roof.photos?.map(photo=>photoCard(photo,roof))}</div><button onClick={()=>setDeleting(roof.id)}>Excluir telhado</button>{deleting===roof.id && <div role="alertdialog" aria-label="Excluir telhado?"><p>Excluir {roof.displayId}? As fotos serão preservadas sem vínculo.</p><button onClick={()=>setDeleting(undefined)}>Cancelar</button><button onClick={()=>{onChange({...project,roofs:project.roofs?.filter(r=>r.id!==roof.id),detachedRoofPhotos:[...project.detachedRoofPhotos ?? [],...(roof.photos ?? []).map(p=>({...p,linkedEntityType:undefined,linkedEntityId:undefined,roofId:undefined}))]});setDeleting(undefined);setOffer(undefined)}}>Confirmar exclusão</button></div>}
      {offer===roof.id && <PhotoOffer key={roof.id} request={{roomId:roof.id,type:'roof',entityId:roof.id,label:`${roof.displayId} — ${roof.name}`}} onAdd={photo=>{const owner=latest.current.roofs?.find(r=>r.id===roof.id);if(!owner)throw new Error('O telhado foi excluído.');const next={...latest.current,roofs:latest.current.roofs?.map(r=>r.id===roof.id?{...r,photos:[...owner.photos ?? [],{...photo,roomId:'',roofId:roof.id}]}:r)};latest.current=next;onChange(next)}} onClose={()=>setOffer(undefined)}/>}</div><RoofSketch roof={roof}/></div>}
    {!!project.detachedRoofPhotos?.length && <details><summary>Fotos de telhados sem vínculo ({project.detachedRoofPhotos.length})</summary><div className="photo-grid">{project.detachedRoofPhotos.map(photo=>photoCard(photo))}</div></details>}{view && <FullPhoto photo={view} onClose={()=>setView(undefined)}/>}
  </section>
}
