import DrawingOrderList from './DrawingOrderList'
import type { PdfOutputMode } from './pdf/compositions'
import { createPortal } from 'react-dom'
import { useEffect,useMemo,useRef,useState } from 'react'
import type { PointerEvent as ReactPointerEvent } from 'react'
import type { Project } from './models'
import { downloadBlob } from './exporting'
import { buildPdf } from './pdf/pdfWriter'
import type { PdfSceneItem } from './pdf/pdfWriter'
import { composeSheet,sheetSourceKey,sheetSourceName } from './pdf/sheetComposer'
import type { SheetSource } from './pdf/sheetComposer'
import { defaultSheetLayout,sheetOption } from './pdf/sheetSettings'
import type { SheetLayout,TitleBlockField } from './pdf/sheetSettings'
import { SHEETS,SCALES,paperSize,orientationNames } from './pdf/sheetLayout'
import type { SheetSize,Orientation,SheetOption } from './pdf/sheetLayout'
import type { PdfLayers } from './pdf/sheetDecorations'
const layerNames:Record<keyof PdfLayers,string>={walls:'Paredes',ids:'IDs',names:'Nomes de ambientes/elementos',measurements:'Medidas',openings:'Portas/janelas/vãos',objects:'Objetos e móveis',equipment:'Equipamentos',structural:'Elementos estruturais',beams:'Vigas',columns:'Pilares',annotations:'Ângulos, diagonais e anotações'}
const fieldNames:Record<TitleBlockField,string>={title:'Título',project:'Projeto',floor:'Pavimento',date:'Data',scale:'Escala',sheet:'Folha',responsible:'Responsável',scaleBar:'Barra de escala'}
const gray=(n=0)=>`rgb(${Math.round(n*255)},${Math.round(n*255)},${Math.round(n*255)})`
function Primitive({item,selected}:{item:PdfSceneItem;selected:string}) {
 if(item.kind==='text')return <text data-label-key={item.section==='drawing'?item.options.key:undefined} x={item.at.x} y={item.at.y} fontSize={item.sizeMm} fontFamily="Helvetica, Arial, sans-serif" fontWeight={item.options.font==='bold'?'bold':'normal'} textAnchor={item.options.align==='center'?'middle':item.options.align==='right'?'end':'start'} fill={selected===item.options.key?'#165aa3':gray(item.options.gray)} transform={`rotate(${item.options.rotate??0} ${item.at.x} ${item.at.y})`}>{item.text}</text>
 const props={stroke:gray(item.style.gray),strokeWidth:item.style.width,strokeDasharray:item.style.dash?.join(' '),fill:'none'}
 switch(item.kind){case 'line':return <line {...props} x1={item.a.x} y1={item.a.y} x2={item.b.x} y2={item.b.y}/>;case 'polyline':return item.close?<polygon {...props} points={item.points.map(p=>`${p.x},${p.y}`).join(' ')}/>:<polyline {...props} points={item.points.map(p=>`${p.x},${p.y}`).join(' ')}/>;case 'rect':return <rect {...props} x={item.x} y={item.y} width={item.w} height={item.h} fill={item.style.fillGray===undefined?'none':gray(item.style.fillGray)} stroke={item.style.stroke===false?'none':props.stroke}/>;case 'circle':return <circle {...props} cx={item.center.x} cy={item.center.y} r={item.r}/>;case 'curve':return <path {...props} d={`M ${item.a.x} ${item.a.y} C ${item.c1.x} ${item.c1.y} ${item.c2.x} ${item.c2.y} ${item.b.x} ${item.b.y}`}/>}
}
export default function SheetPreviewPanel({project,sources:inputSources,initial,preferInitial=false,outputMode='single',outputName,onOrderChange,onChangeProject,onClose}:{project:Project;sources:SheetSource[];initial:SheetLayout;preferInitial?:boolean;outputMode?:PdfOutputMode;outputName?:string;onOrderChange?:(keys:string[])=>void;onChangeProject?:(project:Project)=>void;onClose:()=>void}) {
 const [order,setOrder]=useState(()=>inputSources.map(sheetSourceKey)),[applyKeys,setApplyKeys]=useState(()=>inputSources.map(sheetSourceKey)),[files,setFiles]=useState<{name:string;bytes:Uint8Array}[]>([])
 const sources=order.map(key=>inputSources.find(s=>sheetSourceKey(s)===key)).filter((s):s is SheetSource=>!!s)
 const [index,setIndex]=useState(0),[layouts,setLayouts]=useState<Record<string,SheetLayout>>(()=>Object.fromEntries(sources.map(s=>{const key=sheetSourceKey(s),saved=project.sheetLayouts?.[key];if(!saved)return [key,{...initial,labelOverrides:{},titleBlockPosition:{...initial.titleBlockPosition}}];if(!preferInitial)return [key,saved];const old=paperSize(sheetOption(saved)),next=paperSize(sheetOption(initial)),bottom=Math.abs(saved.titleBlockPosition.y-(old.height-74))<.1;return [key,{...saved,paperSize:initial.paperSize,orientation:initial.orientation,scale:initial.scale,visibleLayers:initial.visibleLayers,responsible:initial.responsible??saved.responsible,titleBlockPosition:{x:Math.max(10,Math.min(saved.titleBlockPosition.x,next.width-Math.min(180,next.width-20)-10)),y:bottom?next.height-74:Math.max(10,Math.min(saved.titleBlockPosition.y,next.height-74))}}]}))),[mode,setMode]=useState<'drawing'|'label'|'title'>('drawing'),[selected,setSelected]=useState(''),[message,setMessage]=useState('')
 const source=sources[index],key=sheetSourceKey(source),layout=layouts[key]??defaultSheetLayout(),svg=useRef<SVGSVGElement>(null),projectRef=useRef(project),layoutsRef=useRef(layouts),session=useRef<{id:number;x:number;y:number;start:SheetLayout;mode:typeof mode;label:string}|undefined>(undefined)
 projectRef.current=project;layoutsRef.current=layouts
 const prepared=useMemo(()=>{try{return {result:composeSheet(project,source,layout,{index,total:outputMode==='separate'?1:sources.length}),error:''}}catch(e){return {result:undefined,error:e instanceof Error?e.message:'Não foi possível preparar a prancha.'}}},[project,source,layout,index,sources.length,outputMode])
 const result=prepared.result,page=result?.page,paper=paperSize(sheetOption(layout)),label=page?.scene.find((i):i is Extract<PdfSceneItem,{kind:'text'}>=>i.kind==='text'&&i.options.key===selected),override=layout.labelOverrides[selected]??{dx:0,dy:0}
 function save(next:SheetLayout,persist=true){const all={...layoutsRef.current,[key]:next};layoutsRef.current=all;setLayouts(all);if(persist)onChangeProject?.({...projectRef.current,sheetLayouts:{...projectRef.current.sheetLayouts,...all}});setMessage('');setFiles([])}
 function close(){onChangeProject?.({...projectRef.current,sheetLayouts:{...projectRef.current.sheetLayouts,...layoutsRef.current}});onClose()}
 useEffect(()=>{const bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!session.current)close()};window.addEventListener('keydown',esc);return()=>{document.body.style.overflow=bodyOverflow;window.removeEventListener('keydown',esc)}},[onClose])
 function coordinate(e:ReactPointerEvent<SVGSVGElement>){const matrix=svg.current?.getScreenCTM();if(!matrix)return {x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return {x:p.x,y:p.y}}
 function begin(e:ReactPointerEvent<SVGSVGElement>){if(e.button!==0)return;const labelKey=(e.target as Element).closest('[data-label-key]')?.getAttribute('data-label-key')??'';if(mode==='label'&&!labelKey)return;if(mode==='label')setSelected(labelKey);const p=coordinate(e);session.current={id:e.pointerId,x:p.x,y:p.y,start:layout,mode,label:labelKey};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault()}
 function move(e:ReactPointerEvent<SVGSVGElement>){const s=session.current;if(!s||s.id!==e.pointerId)return;const p=coordinate(e),dx=p.x-s.x,dy=p.y-s.y,next={...s.start};if(s.mode==='drawing'){next.drawingOffsetX+=dx;next.drawingOffsetY+=dy}else if(s.mode==='title')next.titleBlockPosition={x:s.start.titleBlockPosition.x+dx,y:s.start.titleBlockPosition.y+dy};else {const old=s.start.labelOverrides[s.label]??{dx:0,dy:0};next.labelOverrides={...s.start.labelOverrides,[s.label]:{...old,dx:old.dx+dx,dy:old.dy+dy}}}save(next,false)}
 function end(e:ReactPointerEvent<SVGSVGElement>,cancel=false){const s=session.current;if(!s||s.id!==e.pointerId)return;session.current=undefined;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);save(cancel?s.start:layoutsRef.current[key])}
 function changeOption(option:SheetOption){const size=paperSize(option),old=paperSize(sheetOption(layout)),atBottom=Math.abs(layout.titleBlockPosition.y-(old.height-74))<.1;save({...layout,paperSize:option.sheet,orientation:option.orientation,scale:option.scale,titleBlockPosition:{x:Math.max(10,Math.min(layout.titleBlockPosition.x,size.width-Math.min(180,size.width-20)-10)),y:atBottom?size.height-74:Math.max(10,Math.min(layout.titleBlockPosition.y,size.height-74))}})}
 function center(){const b=result?.drawingBounds;if(!b)return;const furniture=page?Math.min(...page.scene.filter(i=>i.section==='legend'||i.section==='title').flatMap(i=>i.kind==='rect'?[i.y]:[])):paper.height-74;const top=furniture< paper.height/2?layout.titleBlockPosition.y+67:10,bottom=furniture<paper.height/2?paper.height-10:furniture-3;save({...layout,drawingOffsetX:layout.drawingOffsetX+paper.width/2-(b.minX+b.maxX)/2,drawingOffsetY:layout.drawingOffsetY+(top+bottom)/2-(b.minY+b.maxY)/2})}
 function reorder(next:string[]){const current=sheetSourceKey(source);setOrder(next);setIndex(Math.max(0,next.indexOf(current)));onOrderChange?.(next);setFiles([]);setMessage('')}
 function applyConfiguration(){const all={...layoutsRef.current};for(const target of applyKeys){if(!all[target])continue;all[target]={...all[target],paperSize:layout.paperSize,orientation:layout.orientation,scale:layout.scale,visibleLayers:{...layout.visibleLayers},titleBlockFields:{...layout.titleBlockFields},titleBlockPosition:{...layout.titleBlockPosition},responsible:layout.responsible}}layoutsRef.current=all;setLayouts(all);onChangeProject?.({...projectRef.current,sheetLayouts:{...projectRef.current.sheetLayouts,...all}});setFiles([]);setMessage(`Configuração aplicada a ${applyKeys.length} página(s). Posições e ajustes individuais dos rótulos foram preservados.`)}
 const fileSlug=(name:string)=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_|_$/g,'')||'Levantamento'
 function download(file:{name:string;bytes:Uint8Array}){downloadBlob(file.name,new Blob([file.bytes as BlobPart],{type:'application/pdf'}))}
 function exportPdf(){try{const pages=sources.map((s,i)=>composeSheet(project,s,layoutsRef.current[sheetSourceKey(s)]??initial,{index:i,total:outputMode==='separate'?1:sources.length}));const bad=pages.findIndex(p=>p.clipped);if(bad>=0){setIndex(bad);throw new Error('Há conteúdo fora das margens nesta folha. Mova o desenho/carimbo ou escolha outra folha/escala.')}const generated=outputMode==='single'?[{bytes:buildPdf(pages.map(p=>p.page),project.name),name:`${fileSlug(outputName??project.name)}.pdf`}]:pages.map((p,i)=>({bytes:buildPdf(p.page,sheetSourceName(sources[i])),name:`${String(i+1).padStart(2,'0')}_${fileSlug(sheetSourceName(sources[i]))}.pdf`}));setFiles(generated);for(const file of generated)download(file);onChangeProject?.({...projectRef.current,sheetLayouts:{...projectRef.current.sheetLayouts,...layoutsRef.current}});setMessage(outputMode==='single'?'PDF gerado na ordem selecionada, com as configurações próprias de cada página.':'PDFs separados gerados. Se o navegador limitar vários downloads, use os botões abaixo.')}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível gerar o PDF.')}}
 const updateLabel=(value:Partial<typeof override>)=>save({...layout,labelOverrides:{...layout.labelOverrides,[selected]:{...override,...value}}})
 return createPortal(<div className="sheet-preview-overlay" role="dialog" aria-modal="true" aria-label="Prévia de prancha"><header className="sheet-preview-header"><div><span className="eyebrow">PLANTA / CROQUI → PRÉVIA DE PRANCHA → PDF</span><h2>Prévia de prancha</h2></div><button onClick={close}>Voltar ao levantamento</button></header><div className="sheet-preview-body"><aside className="sheet-preview-settings">
 <h3>Páginas do PDF</h3><DrawingOrderList keys={sources.map(sheetSourceKey)} names={Object.fromEntries(sources.map(s=>[sheetSourceKey(s),sheetSourceName(s)]))} active={key} onSelect={selected=>{setIndex(sources.findIndex(s=>sheetSourceKey(s)===selected));setSelected('');setMessage('')}} onReorder={reorder}/>
 {sources.length>1&&<details><summary>Aplicar configuração a outras páginas</summary><button onClick={()=>setApplyKeys(sources.map(sheetSourceKey))}>Selecionar todas</button><button onClick={()=>setApplyKeys([])}>Limpar</button>{sources.map(s=>{const k=sheetSourceKey(s);return <label className="sheet-check" key={k}><input type="checkbox" checked={applyKeys.includes(k)} onChange={e=>setApplyKeys(old=>e.target.checked?[...old,k]:old.filter(x=>x!==k))}/>{sheetSourceName(s)}</label>})}<p>Papel, orientação, escala, camadas e padrão de carimbo. Não copia posições do desenho nem ajustes de rótulos.</p><button disabled={!applyKeys.length} onClick={applyConfiguration}>Aplicar esta configuração às páginas selecionadas</button></details>}
 <h3>{sheetSourceName(source)}</h3><label>Formato<select value={layout.paperSize} onChange={e=>changeOption({...sheetOption(layout),sheet:e.target.value as SheetSize})}>{(Object.keys(SHEETS) as SheetSize[]).map(s=><option key={s}>{s}</option>)}</select></label><label>Orientação<select value={layout.orientation} onChange={e=>changeOption({...sheetOption(layout),orientation:e.target.value as Orientation})}>{(['portrait','landscape'] as const).map(o=><option key={o} value={o}>{orientationNames[o]}</option>)}</select></label><label>Escala física<select value={layout.scale} onChange={e=>changeOption({...sheetOption(layout),scale:Number(e.target.value)})}>{SCALES.map(s=><option key={s} value={s}>1:{s}</option>)}</select></label>
 <p className="muted">{paper.width} × {paper.height} mm · Margens de 10 mm. 5 m = {(5000/layout.scale).toLocaleString('pt-BR',{maximumFractionDigits:3})} mm no papel.</p>
 <div className="sheet-edit-modes">{([['drawing','Mover desenho'],['label','Ajustar rótulos'],['title','Mover carimbo']] as const).map(([v,t])=><button key={v} aria-pressed={mode===v} className={mode===v?'primary':''} onClick={()=>setMode(v)}>{t}</button>)}<button onClick={center}>Centralizar desenho</button></div>
 {mode==='drawing'&&<div className="pdf-options">{(['drawingOffsetX','drawingOffsetY'] as const).map((v,i)=><label key={v}>Deslocamento {i?'Y':'X'} (mm)<input type="number" step="1" value={Math.round(layout[v]*100)/100} onChange={e=>save({...layout,[v]:Number(e.target.value)})}/></label>)}</div>}
 {mode==='label'&&<><p>Clique e arraste um texto. Esses ajustes pertencem somente à prancha.</p>{label&&<><strong>{label.text}</strong><div className="pdf-options">{(['dx','dy'] as const).map(v=><label key={v}>{v==='dx'?'Horizontal':'Vertical'} (mm)<input type="number" step="1" value={Math.round(override[v]*100)/100} onChange={e=>updateLabel({[v]:Number(e.target.value)})}/></label>)}<label>Rotação (°)<input type="number" value={override.rotation??label.options.rotate??0} onChange={e=>updateLabel({rotation:Number(e.target.value)})}/></label></div><button onClick={()=>{const next={...layout.labelOverrides};delete next[selected];save({...layout,labelOverrides:next})}}>Restaurar rótulo do croqui/planta</button></>}</>}
 <details open={mode==='title'}><summary>Carimbo e observações</summary><label>Posição<select value="" onChange={e=>{const top=e.target.value.startsWith('top'),right=e.target.value.endsWith('right');save({...layout,titleBlockPosition:{x:right?paper.width-Math.min(180,paper.width-20)-10:10,y:top?10:paper.height-74}})}}><option value="" disabled>Escolher posição…</option><option value="bottom-left">Inferior esquerdo</option><option value="bottom-right">Inferior direito</option><option value="top-left">Superior esquerdo</option><option value="top-right">Superior direito</option></select></label><div className="pdf-options">{(['x','y'] as const).map(v=><label key={v}>{v.toUpperCase()} do carimbo (mm)<input type="number" value={Math.round(layout.titleBlockPosition[v]*100)/100} onChange={e=>save({...layout,titleBlockPosition:{...layout.titleBlockPosition,[v]:Number(e.target.value)}})}/></label>)}</div>{(Object.keys(fieldNames) as TitleBlockField[]).map(v=><label className="sheet-check" key={v}><input type="checkbox" checked={layout.titleBlockFields[v]} onChange={e=>save({...layout,titleBlockFields:{...layout.titleBlockFields,[v]:e.target.checked}})}/>{fieldNames[v]}</label>)}<label>Responsável<input value={layout.responsible??project.generalChecks?.responsible?.value??''} onChange={e=>save({...layout,responsible:e.target.value})}/></label><label>Observação manual (até 200 caracteres)<textarea maxLength={200} value={layout.notes} onChange={e=>save({...layout,notes:e.target.value})}/></label></details>
 {<details><summary>Visibilidade só nesta prancha</summary>{(Object.keys(layerNames) as (keyof PdfLayers)[]).filter(k=>source.kind!=='roof'||['ids','names','measurements','annotations'].includes(k)).map(v=><label className="sheet-check" key={v}><input type="checkbox" checked={layout.visibleLayers[v]!==false} onChange={e=>save({...layout,visibleLayers:{...layout.visibleLayers,[v]:e.target.checked}})}/>{layerNames[v]}</label>)}</details>}
 {prepared.error&&<p role="alert" className="pdf-warning">{prepared.error}</p>}{result?.clipped&&<p role="alert" className="pdf-warning">Há conteúdo fora das margens. Mova-o ou escolha outra folha/escala. Nenhuma dimensão foi ajustada.</p>}{result?.overlaps&&<p className="pdf-warning">O desenho pode sobrepor o carimbo ou a legenda. Ajuste a posição antes de exportar.</p>}
 <button className="primary" disabled={!page||result?.clipped} onClick={exportPdf}>{outputMode==='separate'?'Gerar PDFs separados':'Gerar PDF'}{sources.length>1?` (${sources.length} folhas)`:''}</button>{message&&<p role="status">{message}</p>}{files.length>1&&files.map(file=><button key={file.name} onClick={()=>download(file)}>Baixar {file.name}</button>)}<p className="muted">Imprimir em 100% / Tamanho real para preservar a escala.</p>
 </aside><section className="sheet-preview-canvas"><p className="sheet-preview-hint">{mode==='drawing'?'Arraste para mover o desenho, sem mudar a escala.':mode==='title'?'Arraste para posicionar o carimbo.':'Clique e arraste um rótulo para ajustá-lo na prancha.'}</p>{page&&<svg ref={svg} viewBox={`0 0 ${page.widthMm} ${page.heightMm}`} className={`sheet-paper mode-${mode}`} role="img" aria-label="Folha real com desenho vetorial, margens e carimbo" onPointerDown={begin} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)}><rect width={page.widthMm} height={page.heightMm} fill="white"/><rect x={10} y={10} width={page.widthMm-20} height={page.heightMm-20} fill="none" stroke="#b7c3ce" strokeWidth={.25} strokeDasharray="2 1"/>{page.scene.map((item,i)=><Primitive key={i} item={item} selected={selected}/>)}</svg>}</section></div></div>,document.body)
}
