import { describe,it,expect } from 'vitest'
import { renderToStaticMarkup } from 'react-dom/server'
import { roomFrom,opening } from '../etapa11/helpers'
import type { Project,SpatialConnection } from '../../src/models'
import { buildRoomGeometry } from '../../src/roomGeometry'
import { diagonalSuggestion } from '../../src/diagonalSuggestion'
import { getCorners } from '../../src/corners'
import { openingAvailable,assemblyPlacement,fitOpeningOptions } from '../../src/planAssembly'
import { worldPoint } from '../../src/floorPlan'
import { buildWallFaces,windowFaces } from '../../src/wallFaces'
import { sharedPlanFaces } from '../../src/floorPlanFaces'
import { duplicatePlanOpenings } from '../../src/planOpeningVisibility'
import { markAssemblyChanges,keepAssemblyPosition,recalculateAssembly,promoteDeletedOrigins } from '../../src/assemblyChanges'
import { prepareOpeningConnections } from '../../src/spatialConnections'
import GeometryStatus from '../../src/GeometryStatus'
import Sketch from '../../src/Sketch'
import { createSnapshot,readSnapshot } from '../../src/storage'
const project=(rooms:ReturnType<typeof roomFrom>[]):Project=>({id:'p',name:'Teste',floors:[{id:rooms[0].floorId,name:'Térreo',rooms}],relationships:[]})
function diagonal(room:ReturnType<typeof roomFrom>,lengthM:number|null){const corners=getCorners(room.walls,room.corners);return {id:'diag',cornerIds:[corners[0].id,corners[2].id] as [string,string],lengthM,source:'measured' as const}}
describe('Correções do levantamento A–N',()=>{
 it('B: sugere 5 m em 3 × 4 sem registrar a sugestão',()=>{const room=roomFrom('Sala',[3,4,3,4]),d=diagonal(room,null);expect(diagonalSuggestion(room,d)).toBeCloseTo(5);expect(d.lengthM).toBeNull()})
 it.each([Math.sqrt(32),5,6])('C/D: quadrado com diagonal %s fecha e preserva comprimentos',length=>{const room=roomFrom('Sala',[4,4,4,4]);room.corners=room.corners.map(c=>({...c,angleSource:'assumed'}));room.diagonals=[diagonal(room,length)];const before=structuredClone(room),g=buildRoomGeometry(room).perimeter;expect(g.endpointsMeet).toBe(true);expect(g.closureM).toBeLessThan(1e-8);expect(g.diagonalChecks[0].drawnLengthM).toBeCloseTo(length,7);if(length!==Math.sqrt(32))expect(g.corners[0].angleDegrees).not.toBeCloseTo(90);expect(room).toEqual(before)})
 it('E: diagonal impossível informa erro; ajuste fecha sem apagar medidas',()=>{const room=roomFrom('Sala',[4,4,4,4]);room.diagonals=[diagonal(room,10)];const g=buildRoomGeometry(room).perimeter;expect(renderToStaticMarkup(<GeometryStatus geometry={g}/>)).toContain('Estas medidas não fecham exatamente');const adjusted=buildRoomGeometry({...room,geometryAdjustment:true,perimeterClosed:true}).perimeter;expect(adjusted.closureM).toBe(0);expect(adjusted.residuals.some(r=>r.difference>.01)).toBe(true);expect(room.diagonals[0].lengthM).toBe(10)})
 it.each(['door','gap','window'] as const)('F/G/H: %s está disponível inclusive com par existente',type=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,3,4,3]);a.openings=[opening(a,{type,label:{door:'P01',gap:'V01',window:'J01'}[type]})];b.openings=[opening(b,{type,label:{door:'P02',gap:'V02',window:'J02'}[type]})];const p=project([a,b]);expect(fitOpeningOptions(p,a,b.id).map(o=>o.id)).toEqual([a.openings[0].id]);expect(openingAvailable(p,a.id,a.openings[0].id,b.id)).toBe(true);a.openings[0].connectedRoomId=b.id;a.openings[0].connectedOpeningId=b.openings[0].id;expect(openingAvailable(p,a.id,a.openings[0].id,b.id)).toBe(true);expect(openingAvailable(p,a.id,a.openings[0].id,'third')).toBe(false)})
 it('I/9/N: origem única, encaixe alinhado, aviso e recálculo sem mover vizinho',()=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,3,4,3]);a.openings=[opening(a,{label:'P01',type:'door',offsetM:.5,widthM:.8,heightM:2.1})];b.openings=[opening(b,{label:'P02',type:'door',offsetM:.5,widthM:.8,heightM:2.1})];const oa=a.openings[0],ob=b.openings[0];oa.connectedRoomId=b.id;oa.connectedOpeningId=ob.id;oa.originOpeningId=oa.id;const c:SpatialConnection={id:'c',type:'opening',a:{roomId:a.id,elementId:oa.id},b:{roomId:b.id,elementId:ob.id},assembly:true};let p=prepareOpeningConnections({...project([a,b]),spatialConnections:[c]});const fixed={roomId:a.id,floorId:a.floorId,x:0,y:0,rotation:0},fit=assemblyPlacement(p,c,fixed)!;p={...p,roomPlacements:[fixed,fit]};expect(fit.rotation).toBe(180);const ga=buildRoomGeometry(a),gb=buildRoomGeometry(b),ap=worldPoint(ga.openings.placements[0].start,fixed),bp=worldPoint(gb.openings.placements[0].end,fit);expect(Math.hypot(ap.x-bp.x,ap.y-bp.y)).toBeLessThan(1e-8);expect(duplicatePlanOpenings(p,a.floorId,p.roomPlacements!)).toEqual(new Set([`${b.id}:${ob.id}`]));expect(renderToStaticMarkup(<Sketch room={a} survey={ga}/>)).toContain(oa.label);expect(renderToStaticMarkup(<Sketch room={b} survey={gb}/>)).toContain(ob.label);const next={...p,floors:p.floors.map(f=>({...f,rooms:f.rooms.map(r=>r.id===b.id?{...r,openings:r.openings.map(o=>({...o,offsetM:1}))}:r)}))},marked=markAssemblyChanges(next,p);expect(marked.geometryChangedRoomIds).toContain(b.id);expect(marked.roomPlacements).toEqual(p.roomPlacements);expect(keepAssemblyPosition(marked,b.id).geometryChangedRoomIds).toEqual([]);const result=recalculateAssembly(marked,b.id);expect(result.error).toBeUndefined();expect(result.project.roomPlacements?.find(p=>p.roomId===a.id)).toEqual(fixed);expect(result.project.roomPlacements?.find(p=>p.roomId===b.id)?.x).not.toBe(fit.x);const removed={...p,floors:p.floors.map(f=>({...f,rooms:f.rooms.map(r=>r.id===a.id?{...r,openings:[]}:r)}))};let asked=false;const promoted=promoteDeletedOrigins(removed,p,()=>{asked=true;return true});expect(asked).toBe(true);expect(promoted.floors[0].rooms[1].openings[0].originOpeningId).toBe(ob.id)})
 it('J: conserva parte exclusiva de parede 4 m compartilhada com 2,5 m',()=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Anexo',[2.5,2,2.5,2]);for(const r of [a,b])r.walls.forEach(w=>w.thickness=.15);const p={...project([a,b]),relationships:[{id:'r',type:'shared_wall' as const,sourceRoomId:a.id,sourceElementId:a.walls[0].id,targetRoomId:b.id,targetElementId:b.walls[0].id}]},placements=[{roomId:a.id,floorId:a.floorId,x:0,y:0,rotation:0},{roomId:b.id,floorId:b.floorId,x:2.5,y:-.15,rotation:180}],result=sharedPlanFaces(p,a.floorId,placements);expect(result.faces).toHaveLength(1);const horizontal=result.faces[0].ranges.filter(r=>Math.abs(r.start.y-r.end.y)<1e-8);expect(horizontal.some(r=>Math.min(r.start.x,r.end.x)<=2.5+1e-8&&Math.max(r.start.x,r.end.x)>=4-1e-8)).toBe(true);expect(horizontal.filter(r=>Math.min(r.start.x,r.end.x)<=0&&Math.max(r.start.x,r.end.x)>=4)).toHaveLength(2);expect(a.walls[0].lengthM).toBe(4);expect(b.walls[0].lengthM).toBe(2.5)})
 it('K/L/M: espessura física, ombreiras e tampas livres',()=>{const segment={id:'w',start:{x:0,y:0},end:{x:4,y:0},thickness:.15,referenceFace:'internal' as const};expect(buildWallFaces([segment]).get('w')).toHaveLength(4);const ranges=new Map([['w',[{start:{x:0,y:0},end:{x:1,y:0}},{start:{x:2,y:0},end:{x:4,y:0}}]]]),faces=buildWallFaces([segment],ranges).get('w')!;expect(faces).toHaveLength(8);for(const x of [0,1,2,4])expect(faces.some(f=>f.start.x===x&&f.end.x===x&&Math.abs(f.start.y-f.end.y)===.15)).toBe(true);const window=windowFaces(segment,{x:1,y:0},{x:2,y:0});expect(window[0].start.y).toBe(0);expect(window.at(-1)!.start.y).toBe(-.15)})
 it('F: portas, vãos e janelas aparecem juntos na lista',()=>{const a=roomFrom('Sala',[4,3,4,3]),b=roomFrom('Cozinha',[4,3,4,3]);for(const type of ['door','gap','window'] as const)opening(a,{type,label:type});expect(fitOpeningOptions(project([a,b]),a,b.id).map(o=>o.label)).toEqual(['door — Porta','gap — Vão','window — Janela'])})
 it('persistência mantém origem, travas e avisos',()=>{const room=roomFrom('Sala',[4,3,4,3]),p={...project([room]),geometryChangedRoomIds:[room.id],planPreferences:{[room.floorId]:{locked:true}}};room.openings=[opening(room,{label:'P01',type:'door',originOpeningId:'origin'})];const snapshot=createSnapshot({projects:[p],projectId:p.id,floorId:room.floorId,roomId:room.id});expect(readSnapshot(JSON.parse(JSON.stringify(snapshot))).data.projects).toEqual([p])})
})
